const fs = require('fs');
const base = 'C:/Users/user/Desktop/클로드/gemkorea/';
const now = new Date().toISOString().slice(0,19);

const newExps = [
  // 승마/자연 레포츠
  {experience_id:'EX-GG-EQU-001',name:'제주 승마 체험 (성읍민속마을)',category_main:'문화/체험',category_sub:'승마/레포츠',region_main:'JJ',region_sub:'제주특별자치도 서귀포시',address:'제주특별자치도 서귀포시 표선면 성읍리 일원',lat:33.3861,lng:126.8011,price:'1인 20,000원~',duration:'30분~1시간',reservation_required:false,target_user:['가족','어린이','커플'],nearby_places:[],related_heritage_ids:[],short_description:'제주 조랑말의 고장 성읍민속마을 인근에서 제주 전통 조랑말 승마를 체험하는 프로그램이다. 제주 재래종 조랑말은 작고 온순해 어린이도 탑승할 수 있으며, 한라산을 배경으로 한 오름 사이 초지에서 진행된다.',source_urls:['https://www.visitjeju.net/'],data_confidence:'high',tags:['승마','제주조랑말','성읍민속마을','제주','가족체험','오름','한라산'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~18:00',phone:''},
  {experience_id:'EX-GW-EQU-001',name:'홍천 승마 체험 (홍천강 승마클럽)',category_main:'문화/체험',category_sub:'승마/레포츠',region_main:'GW',region_sub:'강원특별자치도 홍천군',address:'강원특별자치도 홍천군 홍천읍 홍천강변길 일원',lat:37.6965,lng:127.8868,price:'1인 25,000원~',duration:'1시간',reservation_required:true,target_user:['가족','개인','커플'],nearby_places:[],related_heritage_ids:[],short_description:'홍천강 풍경을 배경으로 승마를 즐기는 체험 프로그램이다. 전문 교관의 기초 교육 후 강변 승마 코스를 진행하며, 홍천강 수영과 레프팅과 연계한 패키지로도 운영된다.',source_urls:['https://www.hongcheon.go.kr/'],data_confidence:'high',tags:['승마','홍천','강원','홍천강','가족여행','승마체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~17:00',phone:'033-430-2700'},
  // 글램핑/캠핑
  {experience_id:'EX-GG-CAM-001',name:'가평 글램핑 (북한강변)',category_main:'문화/체험',category_sub:'캠핑/글램핑',region_main:'GG',region_sub:'경기도 가평군',address:'경기도 가평군 가평읍 북한강변길 일원',lat:37.8306,lng:127.5108,price:'1박 100,000원~',duration:'1박 2일',reservation_required:true,target_user:['커플','가족'],nearby_places:[],related_heritage_ids:[],short_description:'북한강 바로 앞에서 텐트와 침대, 에어컨까지 갖춘 럭셔리 글램핑을 즐기는 체험이다. 수도권에서 1시간 거리로 접근성이 좋고, 강수영·카약과 연계한 패키지로 운영된다.',source_urls:['https://www.gapyeong.go.kr/'],data_confidence:'high',tags:['글램핑','가평','북한강','경기','캠핑','커플여행','수도권근교'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'연중 (예약 필수)',phone:''},
  {experience_id:'EX-GW-CAM-001',name:'양양 서핑 글램핑',category_main:'문화/체험',category_sub:'캠핑/글램핑',region_main:'GW',region_sub:'강원특별자치도 양양군',address:'강원특별자치도 양양군 현남면 인구리 해변 일원',lat:38.0783,lng:128.7112,price:'1박 120,000원~',duration:'1박 2일',reservation_required:true,target_user:['커플','청년'],nearby_places:[],related_heritage_ids:[],short_description:'양양 인구해변 바로 앞 글램핑에서 숙박하고 아침 서핑 강습을 세트로 즐기는 프로그램이다. 파도 소리 들으며 잠들고 아침에 일어나 서핑까지 — 동해안 최고의 힐링 코스로 꼽힌다.',source_urls:['https://www.yangyang.go.kr/tour/'],data_confidence:'high',tags:['서핑글램핑','양양','강원','인구해변','동해','커플','힐링'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'5~10월',phone:''},
  // 천문대/별 관측
  {experience_id:'EX-GW-STR-001',name:'영월 별마로 천문대',category_main:'문화/체험',category_sub:'과학체험',region_main:'GW',region_sub:'강원특별자치도 영월군',address:'강원특별자치도 영월군 영월읍 천문대길 397',lat:37.1858,lng:128.4719,price:'성인 7,000원',duration:'1~2시간',reservation_required:false,target_user:['가족','커플','개인'],nearby_places:[],related_heritage_ids:[],short_description:'해발 799m 봉래산 정상에 위치한 국내 최대 규모의 공공 천문대다. 80cm 주망원경으로 행성·성운·은하를 직접 관측하고 천문 해설사의 생생한 설명을 들을 수 있으며, 맑은 날 영월의 밤하늘은 별이 쏟아지는 것 같다.',source_urls:['https://www.ywao.go.kr/'],data_confidence:'high',tags:['별마로천문대','영월','강원','별관측','천문대','은하수','야경'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'14:00~22:00 (화요일 휴관)',phone:'033-372-8445'},
  {experience_id:'EX-GN-STR-001',name:'합천 국제천문대',category_main:'문화/체험',category_sub:'과학체험',region_main:'GN',region_sub:'경상남도 합천군',address:'경상남도 합천군 가야면 황매산천문대로 129',lat:35.5014,lng:127.9478,price:'성인 5,000원',duration:'1~2시간',reservation_required:false,target_user:['가족','커플','개인'],nearby_places:[],related_heritage_ids:[],short_description:'황매산 해발 600m에 위치한 천문대로 도심 빛 공해가 거의 없어 남부 지역 최고의 별 관측지로 꼽힌다. 봄에는 황매산 철쭉과 별 관측을 함께 즐길 수 있어 특별한 경험이 된다.',source_urls:['https://www.hc.go.kr/'],data_confidence:'high',tags:['합천천문대','황매산','경남','별관측','천문대','철쭉','남부천문'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'14:00~22:00 (화요일 휴관)',phone:'055-930-3266'},
  // 해루질/야간 갯벌
  {experience_id:'EX-IC-OCN-001',name:'강화도 야간 해루질 체험',category_main:'문화/체험',category_sub:'해양체험',region_main:'IC',region_sub:'인천광역시 강화군',address:'인천광역시 강화군 화도면 동막리 갯벌',lat:37.5769,lng:126.4436,price:'1인 20,000원',duration:'2~3시간',reservation_required:true,target_user:['가족','개인'],nearby_places:[],related_heritage_ids:[],short_description:'밤에 헤드랜턴을 쓰고 갯벌에 나가 꽃게·낙지·바지락을 손으로 잡는 해루질 체험이다. 서해 강화 갯벌의 야간 생태계를 관찰하고 직접 잡은 해산물을 즉석에서 구워 먹는 특별한 경험이다.',source_urls:['https://www.ganghwa.go.kr/'],data_confidence:'high',tags:['해루질','강화도','인천','야간갯벌','꽃게','낙지','서해체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'4~10월 (썰물 시간대)',phone:'032-934-7887'},
  // 전통 과거시험/한국문화 체험
  {experience_id:'EX-JB-CUL-001',name:'전주 조선 과거시험 체험',category_main:'문화/체험',category_sub:'역사 체험',region_main:'JB',region_sub:'전라북도 전주시',address:'전라북도 전주시 완산구 교동 한옥마을 일원',lat:35.8147,lng:127.1524,price:'1인 10,000원',duration:'1~2시간',reservation_required:true,target_user:['가족','어린이','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'전주 한옥마을에서 조선 시대 과거시험을 재현하는 문화 체험이다. 한복 착용 후 붓글씨로 사자성어를 쓰고 장원급제 합격증을 받는 프로그램으로 외국인 방문객에게 특히 인기가 높다.',source_urls:['https://www.jeonju.go.kr/'],data_confidence:'high',tags:['과거시험체험','전주','한옥마을','조선시대','한복','역사체험','외국인'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~17:00 (월요일 휴무)',phone:'063-281-2114'},
  {experience_id:'EX-SE-CUL-001',name:'서울 한국의 집 전통 공연·한식',category_main:'문화/체험',category_sub:'문화예술',region_main:'SE',region_sub:'서울특별시 중구',address:'서울특별시 중구 필동로1길 5',lat:37.5605,lng:126.9977,price:'공연+한식 1인 50,000원~',duration:'2~3시간',reservation_required:true,target_user:['외국인','커플','개인'],nearby_places:[],related_heritage_ids:[],short_description:'조선 시대 양식으로 복원된 고택에서 전통 공연(가야금·사물놀이·탈춤)을 관람하고 전통 한정식을 즐기는 고급 문화 체험이다. 외국인 방문객이 가장 많이 찾는 한국 전통 문화 체험 1번지다.',source_urls:['https://www.koreahouse.or.kr/'],data_confidence:'high',tags:['한국의집','서울','한정식','전통공연','가야금','외국인체험','중구'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'17:30·19:30 공연 (월요일 휴무)',phone:'02-2266-9101'},
  // 자전거/트레킹
  {experience_id:'EX-GW-CYC-001',name:'춘천 자전거길 의암호 투어',category_main:'문화/체험',category_sub:'어드벤처/레포츠',region_main:'GW',region_sub:'강원특별자치도 춘천시',address:'강원특별자치도 춘천시 신동면 중도삼거리길 (의암댐 자전거 대여소)',lat:37.8895,lng:127.7197,price:'자전거 대여 1인 5,000원~',duration:'2~3시간',reservation_required:false,target_user:['가족','커플','개인'],nearby_places:[],related_heritage_ids:[],short_description:'의암호를 따라 달리는 춘천 자전거길로 호수와 산이 어우러진 경치가 아름답다. 소양강 스카이워크·구봉산 전망대와 연계하여 자전거 투어를 즐길 수 있으며 봄 벚꽃 시즌이 절정이다.',source_urls:['https://www.chuncheon.go.kr/'],data_confidence:'high',tags:['의암호','춘천','자전거','강원','자전거투어','호수','봄나들이'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'연중 (자전거 대여: 09:00~18:00)',phone:'033-251-2533'},
  {experience_id:'EX-JJ-CYC-001',name:'제주 올레길 트레킹 (7코스 외돌개)',category_main:'문화/체험',category_sub:'자연체험',region_main:'JJ',region_sub:'제주특별자치도 서귀포시',address:'제주특별자치도 서귀포시 서홍동 외돌개 일원',lat:33.2436,lng:126.5180,price:'무료',duration:'3~4시간',reservation_required:false,target_user:['개인','커플','가족'],nearby_places:[],related_heritage_ids:[],short_description:'제주 올레길 7코스 중 외돌개~월평 구간은 해안 절벽을 따라 걷는 제주 최고의 트레킹 코스다. 기기묘묘한 바위 형태, 쪽빛 바다, 주상절리가 연속으로 펼쳐지며 국내외 트레커들이 가장 선호하는 코스다.',source_urls:['https://www.jejuolle.org/'],data_confidence:'high',tags:['제주올레','외돌개','7코스','트레킹','제주','서귀포','해안길'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'연중',phone:'064-762-2190'},
  // 한국 전통 혼례
  {experience_id:'EX-SE-WED-001',name:'서울 전통 혼례 체험 (남산한옥마을)',category_main:'문화/체험',category_sub:'문화예술',region_main:'SE',region_sub:'서울특별시 중구',address:'서울특별시 중구 퇴계로34길 28 (남산한옥마을)',lat:37.5503,lng:126.9936,price:'1인 15,000원~',duration:'1~2시간',reservation_required:true,target_user:['커플','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'남산한옥마을에서 조선 시대 전통 혼례를 재현 체험하는 프로그램이다. 신랑·신부 한복 착용 후 전통 혼례 절차(초례·합근례)를 직접 수행하고 기념 사진을 찍는다. 외국인 커플에게 특히 인기다.',source_urls:['https://www.namsanhanok.com/'],data_confidence:'high',tags:['전통혼례','남산한옥마을','서울','한복','외국인체험','결혼체험','조선시대'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~17:00 (토·일·공휴일 운영)',phone:'02-2261-0517'},
  // 야간 한옥 투어
  {experience_id:'EX-GB-NIG-001',name:'경주 동궁과 월지 야간 개장',category_main:'문화/체험',category_sub:'역사 체험',region_main:'GB',region_sub:'경상북도 경주시',address:'경상북도 경주시 원화로 102',lat:35.8340,lng:129.2254,price:'성인 3,000원',duration:'1~2시간',reservation_required:false,target_user:['커플','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'신라 문무왕 때 조성된 별궁 연못에 야간 조명이 켜지면 수면 반사로 두 배의 궁궐 풍경이 펼쳐진다. 국내 야경 명소 1위로 자주 선정되며 천 년 신라 궁궐의 밤 분위기를 경험할 수 있다.',source_urls:['https://www.gyeongju.go.kr/'],data_confidence:'high',tags:['동궁과월지','경주','야경','안압지','신라','야간개장','경북'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~22:00 (야간 조명: 일몰~22:00)',phone:'054-779-6100'}
];

const exp = JSON.parse(fs.readFileSync(base+'data/experiences.json','utf8'));
const existingIds = new Set(exp.experiences.map(e=>e.experience_id));
const toAdd = newExps.filter(e=>!existingIds.has(e.experience_id));

exp.experiences.push(...toAdd);
exp.total = exp.experiences.length;
exp._updated = now;
fs.writeFileSync(base+'data/experiences.json', JSON.stringify(exp,null,2),'utf8');

const log = JSON.parse(fs.readFileSync(base+'logs/automation_log.json','utf8'));
log.runs.push({time:now, mode:'B', type:'체험학습', new_collected:toAdd.length, total_experiences:exp.total});
fs.writeFileSync(base+'logs/automation_log.json', JSON.stringify(log,null,2),'utf8');

console.log('체험 장소 추가:', toAdd.length+'개 / 총 체험', exp.total+'개');
toAdd.forEach(e=>console.log('  + ['+e.experience_id+']', e.name, '|', e.category_sub));
