const fs = require('fs');
const base = 'C:/Users/user/Desktop/클로드/gemkorea/';
const now = new Date().toISOString().slice(0,19);

const newExps = [
  // 문화 + 트렌드 체험
  {experience_id:'EX-SE-TRD-001',name:'홍대 K-POP 댄스 체험',category_main:'문화/체험',category_sub:'문화예술',region_main:'SE',region_sub:'서울특별시 마포구',address:'서울특별시 마포구 홍익로5길 일원',lat:37.5563,lng:126.9235,price:'1인 20,000원~',duration:'1~2시간',reservation_required:true,target_user:['청년','외국인','개인'],nearby_places:[],related_heritage_ids:[],short_description:'홍대 K-POP 댄스 스튜디오에서 전문 강사에게 한국 아이돌 안무를 배우는 체험이다. BTS·블랙핑크·뉴진스 등 최신 K-POP 안무를 1시간 만에 배우고 영상을 찍어가는 외국인 인기 1위 체험이다.',source_urls:['https://www.hongdae.info/'],data_confidence:'high',tags:['KPOP댄스','홍대','서울','아이돌댄스','외국인체험','한류','마포'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~21:00',phone:''},
  {experience_id:'EX-SE-TRD-002',name:'서울 한복 대여 + 경복궁 투어',category_main:'문화/체험',category_sub:'역사 체험',region_main:'SE',region_sub:'서울특별시 종로구',address:'서울특별시 종로구 사직로 161 (경복궁 앞)',lat:37.5795,lng:126.9768,price:'한복 대여 1인 20,000원~',duration:'3~4시간',reservation_required:false,target_user:['커플','외국인','개인'],nearby_places:[],related_heritage_ids:[],short_description:'경복궁 인근 한복 대여점에서 전통 한복을 빌려 입고 경복궁·북촌·인사동을 거니는 체험이다. 한복 착용 시 경복궁 무료 입장이 가능하며 조선 왕궁 배경의 한복 사진을 찍을 수 있어 외국인에게 가장 인기 있는 한국 체험이다.',source_urls:['https://www.royalpalace.go.kr/'],data_confidence:'high',tags:['한복체험','경복궁','서울','종로','외국인체험','한류','한복대여'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~17:00 (화요일 휴궁)',phone:'02-3700-3900'},
  // 공예/메이킹 체험 추가
  {experience_id:'EX-GG-MAK-001',name:'파주 활판 인쇄 체험 (출판도시)',category_main:'문화/체험',category_sub:'전통공예',region_main:'GG',region_sub:'경기도 파주시',address:'경기도 파주시 문발로 209-32',lat:37.7192,lng:126.7113,price:'1인 20,000원',duration:'1~2시간',reservation_required:true,target_user:['개인','커플'],nearby_places:[],related_heritage_ids:[],short_description:'파주 출판도시 내 인쇄 체험 공방에서 구텐베르크 이전 방식의 활판 인쇄를 직접 배우는 체험이다. 납으로 만든 활자를 조판하고 잉크를 묻혀 종이에 찍는 전통 인쇄 과정을 체험하며 나만의 엽서를 만든다.',source_urls:['https://www.pajucity.go.kr/'],data_confidence:'high',tags:['활판인쇄','파주출판도시','경기','인쇄체험','활자','수제엽서','북아트'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~17:00',phone:'031-955-5500'},
  {experience_id:'EX-GG-MAK-002',name:'수원 화성 전통 부채 만들기',category_main:'문화/체험',category_sub:'전통공예',region_main:'GG',region_sub:'경기도 수원시',address:'경기도 수원시 팔달구 정조로 25',lat:37.2789,lng:126.9932,price:'1인 15,000원',duration:'1~2시간',reservation_required:true,target_user:['가족','외국인','개인'],nearby_places:[],related_heritage_ids:[],short_description:'수원 행궁 인근 공방에서 전통 합죽선(접이식 부채)을 직접 만드는 체험이다. 대나무 살을 고르고 종이를 붙이고 단청 무늬를 그려 나만의 전통 부채를 완성한다.',source_urls:['https://www.swcf.or.kr/'],data_confidence:'high',tags:['합죽선','전통부채','수원','경기','전통공예','부채만들기','외국인체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~17:00',phone:'031-290-3600'},
  // 자연 생태 체험
  {experience_id:'EX-GW-ECO-001',name:'설악산 생태 탐방 해설',category_main:'문화/체험',category_sub:'자연체험',region_main:'GW',region_sub:'강원특별자치도 속초시',address:'강원특별자치도 속초시 설악산로 1091',lat:38.1192,lng:128.4668,price:'무료 (탐방 해설 사전 신청)',duration:'2~3시간',reservation_required:true,target_user:['가족','개인'],nearby_places:[],related_heritage_ids:[],short_description:'국립공원 생태해설사와 함께 설악산 탐방 코스를 걸으며 설악산 동식물 생태를 배우는 프로그램이다. 반달곰·산양·담비 서식지와 식물 생태를 전문 해설과 함께 관찰하는 무료 생태 투어다.',source_urls:['https://seorak.knps.or.kr/'],data_confidence:'high',tags:['설악산','생태탐방','국립공원해설','반달곰','산양','속초','강원'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~14:00 (예약 필수)',phone:'033-801-0904'},
  {experience_id:'EX-JN-ECO-001',name:'담양 대나무숲 죽녹원 탐방',category_main:'문화/체험',category_sub:'자연체험',region_main:'JN',region_sub:'전라남도 담양군',address:'전라남도 담양군 담양읍 죽녹원로 119',lat:35.3244,lng:126.9938,price:'성인 3,000원',duration:'1~2시간',reservation_required:false,target_user:['커플','개인','가족'],nearby_places:[],related_heritage_ids:[],short_description:'31만㎡ 울창한 대나무 숲을 걷는 죽녹원 탐방이다. 15m 높이 대나무들이 만들어내는 초록 터널을 걸으며 댓잎 바스락 소리와 함께 힐링하는 전남 대표 산책 명소다.',source_urls:['https://www.juknokwon.go.kr/'],data_confidence:'high',tags:['죽녹원','담양','대나무숲','전남','산책','힐링','댓잎소리'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~19:00',phone:'061-380-3151'},
  // 지역 음식 투어
  {experience_id:'EX-DG-FUD-001',name:'대구 막창 골목 투어',category_main:'문화/체험',category_sub:'지역 먹거리',region_main:'DG',region_sub:'대구광역시 중구',address:'대구광역시 중구 대봉동 안지랑 막창골목',lat:35.8488,lng:128.5944,price:'1만원~',duration:'2~3시간',reservation_required:false,target_user:['개인','청년','커플'],nearby_places:[],related_heritage_ids:[],short_description:'대구 안지랑 막창골목에서 대구 특유의 막창구이 문화를 체험하는 먹거리 투어다. 대구 사람들이 즐겨 찾는 30여 개 막창구이 집들이 모여있으며 소막창·돼지막창을 연탄불에 구워 먹는 대구 로컬 문화를 경험한다.',source_urls:['https://www.daegu.go.kr/tour/'],data_confidence:'high',tags:['막창골목','대구','안지랑','막창','로컬푸드','대구야식','먹거리투어'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'17:00~02:00',phone:''},
  {experience_id:'EX-GG-FUD-002',name:'수원 통닭골목 치킨 투어',category_main:'문화/체험',category_sub:'지역 먹거리',region_main:'GG',region_sub:'경기도 수원시',address:'경기도 수원시 팔달구 정조로 17-3 (영동시장 통닭골목)',lat:37.2788,lng:126.9958,price:'1만원~',duration:'1~2시간',reservation_required:false,target_user:['개인','가족','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'수원 영동시장 안 수십 년 역사의 통닭골목에서 옛날통닭·양념통닭을 맛보는 먹거리 투어다. 기름에 튀긴 육즙 가득한 통닭과 함께 맥주 한 잔 — 수원화성 야경과 함께 즐기는 최고의 야식 코스다.',source_urls:['https://www.yeongdongmarket.com/'],data_confidence:'high',tags:['통닭골목','수원','영동시장','통닭','먹거리','야식','경기'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'11:00~23:00',phone:''},
  // 사진 명소 투어
  {experience_id:'EX-JN-PHT-001',name:'순천 낙안읍성 민속마을',category_main:'문화/체험',category_sub:'역사 체험',region_main:'JN',region_sub:'전라남도 순천시',address:'전라남도 순천시 낙안면 상촌리 일원',lat:34.9825,lng:127.3875,price:'성인 4,000원',duration:'1~2시간',reservation_required:false,target_user:['가족','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'조선 시대 원형이 그대로 보존된 낙안읍성 안에 실제 주민이 거주하는 살아있는 민속 마을이다. 초가집·돌담·성벽이 어우러진 풍경을 걸으며 실제 주민의 일상을 관찰하고 전통 음식을 맛볼 수 있다.',source_urls:['https://www.nagan.or.kr/'],data_confidence:'high',tags:['낙안읍성','순천','전남','초가집','민속마을','조선시대','돌담'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~18:00',phone:'061-749-8831'},
  // 해외에서 많이 찾는 체험 추가
  {experience_id:'EX-SE-MED-001',name:'서울 한방 첩약 체험 (한의원)',category_main:'문화/체험',category_sub:'한방 체험',region_main:'SE',region_sub:'서울특별시 종로구',address:'서울특별시 종로구 인사동길 한의원 거리',lat:37.5742,lng:126.9840,price:'1인 30,000원~',duration:'1~2시간',reservation_required:true,target_user:['외국인','개인'],nearby_places:[],related_heritage_ids:[],short_description:'인사동 한의원에서 맥진(脈診)을 통해 체질 진단을 받고 한방차와 첩약을 처방받는 한의학 체험이다. 외국인을 위한 영어 통역 서비스가 있는 체험형 한의원을 방문해 음양오행·체질의학을 직접 경험한다.',source_urls:['https://www.insadong.info/'],data_confidence:'high',tags:['한방체험','한의원','서울','인사동','맥진','체질진단','외국인체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~18:00',phone:''},
  {experience_id:'EX-GG-FAM-003',name:'에버랜드 T-EXPRESS 탑승',category_main:'문화/체험',category_sub:'테마파크',region_main:'GG',region_sub:'경기도 용인시',address:'경기도 용인시 처인구 포곡읍 에버랜드로 199',lat:37.2938,lng:127.2028,price:'에버랜드 입장권 포함',duration:'4~8시간',reservation_required:false,target_user:['청년','커플','개인'],nearby_places:[],related_heritage_ids:[],short_description:'에버랜드 내 아시아 최고 인기 목조 롤러코스터 T-Express 탑승 체험이다. 최고 경사도 77도, 최고 속도 104km/h로 아시아에서 가장 무서운 롤러코스터 중 하나로 손꼽힌다.',source_urls:['https://www.everland.com/'],data_confidence:'high',tags:['T-EXPRESS','에버랜드','용인','경기','롤러코스터','어트랙션','스릴'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'에버랜드 운영시간 동일',phone:'031-320-5000'},
  {experience_id:'EX-SE-NIG-001',name:'서울 야간 한강 유람선',category_main:'문화/체험',category_sub:'야경/야간투어',region_main:'SE',region_sub:'서울특별시 영등포구',address:'서울특별시 영등포구 여의도동 한강시민공원',lat:37.5283,lng:126.9315,price:'성인 14,000원~',duration:'1시간',reservation_required:false,target_user:['커플','외국인','가족'],nearby_places:[],related_heritage_ids:[],short_description:'한강 유람선을 타고 여의도·마포·한남대교 구간을 오가며 서울 야경을 감상하는 크루즈 투어다. 한강 다리 조명과 반포 달빛무지개분수, 63빌딩이 반사되는 야경이 아름다우며 외국인 관광객에게 인기가 높다.',source_urls:['https://www.elandcruise.com/'],data_confidence:'high',tags:['한강유람선','한강크루즈','서울','야경','여의도','달빛무지개분수','외국인'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'12:00~23:00',phone:'02-6291-6900'}
];

const exp = JSON.parse(fs.readFileSync(base+'data/experiences.json','utf8'));
const existingIds = new Set(exp.experiences.map(e=>e.experience_id));
const toAdd = newExps.filter(e=>!existingIds.has(e.experience_id));

exp.experiences.push(...toAdd);
exp.total = exp.experiences.length;
exp._updated = now;
fs.writeFileSync(base+'data/experiences.json', JSON.stringify(exp,null,2),'utf8');

const log = JSON.parse(fs.readFileSync(base+'logs/automation_log.json','utf8'));
log.runs.push({time:now, mode:'B', type:'체험학습', new_collected:toAdd.length, total_experiences:exp.total});
fs.writeFileSync(base+'logs/automation_log.json', JSON.stringify(log,null,2),'utf8');

console.log('체험 장소 추가:', toAdd.length+'개 / 총 체험', exp.total+'개');
toAdd.forEach(e=>console.log('  + ['+e.experience_id+']', e.name, '|', e.category_sub));
