const fs = require('fs');
const base = 'C:/Users/user/Desktop/클로드/gemkorea/';
const now = new Date().toISOString().slice(0,19);

const newExps = [
  // 사진/영상 투어 체험
  {experience_id:'EX-SE-PHT-001',name:'서울 야경 사진 투어 (N서울타워)',category_main:'문화/체험',category_sub:'문화예술',region_main:'SE',region_sub:'서울특별시 중구',address:'서울특별시 중구 남산공원길 105',lat:37.5512,lng:126.9882,price:'N서울타워 입장 성인 16,000원',duration:'2~3시간',reservation_required:false,target_user:['커플','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'N서울타워 전망대에서 서울 야경을 감상하고 사진을 찍는 투어다. 360도 회전 전망대에서 한강·강남·북악산이 한눈에 펼쳐지며 남산케이블카 탑승, 자물쇠 공원 방문까지 남산 야경 코스 전체를 즐길 수 있다.',source_urls:['https://www.nseoultower.co.kr/'],data_confidence:'high',tags:['N서울타워','남산','야경','서울','전망대','커플','외국인'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~23:00 (금·토 24:00)',phone:'02-3455-9277'},
  {experience_id:'EX-BS-PHT-001',name:'부산 감천문화마을 벽화 투어',category_main:'문화/체험',category_sub:'문화예술',region_main:'BS',region_sub:'부산광역시 사하구',address:'부산광역시 사하구 감내2로 203',lat:35.0975,lng:129.0105,price:'무료 (스탬프 투어 1,000원)',duration:'1~2시간',reservation_required:false,target_user:['개인','커플','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'6·25 피란민이 모여든 산동네가 예술 마을로 변신한 감천문화마을을 탐방하는 투어다. 형형색색 벽화와 좁은 골목길, 스탬프 투어를 즐기며 부산의 역사와 현대 예술이 공존하는 공간을 경험한다.',source_urls:['https://www.gamcheon.or.kr/'],data_confidence:'high',tags:['감천문화마을','부산','벽화마을','사하구','피란민마을','부산야경','골목투어'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~18:00',phone:'051-291-1444'},
  // 요리 체험 추가
  {experience_id:'EX-GG-FUD-001',name:'수원 갈비 만들기 체험',category_main:'문화/체험',category_sub:'발효/음식',region_main:'GG',region_sub:'경기도 수원시',address:'경기도 수원시 팔달구 팔달로 45',lat:37.2779,lng:126.9992,price:'1인 30,000원~',duration:'2~3시간',reservation_required:true,target_user:['가족','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'수원 화성 행궁 인근 요리 체험 센터에서 수원 왕갈비의 전통 양념 레시피를 배우고 직접 갈비를 재워 구워 먹는 체험이다. 정조대왕이 사랑했다는 수원 갈비의 역사를 배우며 한국 바비큐 문화를 체험한다.',source_urls:['https://www.suwon.go.kr/'],data_confidence:'high',tags:['수원갈비','갈비체험','수원','경기','한국바비큐','정조대왕','외국인체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'11:00~18:00',phone:'031-228-4700'},
  {experience_id:'EX-JB-FUD-002',name:'전주 한과·다식 만들기 체험',category_main:'문화/체험',category_sub:'발효/음식',region_main:'JB',region_sub:'전라북도 전주시',address:'전라북도 전주시 완산구 풍남문3길 일원',lat:35.8157,lng:127.1515,price:'1인 15,000원',duration:'1~2시간',reservation_required:true,target_user:['가족','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'전주 한옥마을에서 조선 시대 전통 과자인 한과와 다식을 직접 만드는 체험이다. 참쌀·콩·깨를 주재료로 한과를 빚고 다식판으로 찍어내는 과정을 배우며 전통 茶와 함께 시음한다.',source_urls:['https://www.jeonju.go.kr/'],data_confidence:'high',tags:['한과','다식','전주','한옥마을','전통과자','전북','외국인체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~17:00',phone:'063-282-1330'},
  // 섬 여행 체험
  {experience_id:'EX-IC-ISL-001',name:'인천 강화도 갯벌 낙조 투어',category_main:'문화/체험',category_sub:'자연체험',region_main:'IC',region_sub:'인천광역시 강화군',address:'인천광역시 강화군 화도면 동막리 갯벌',lat:37.5748,lng:126.4421,price:'무료',duration:'2~3시간',reservation_required:false,target_user:['커플','가족','개인'],nearby_places:[],related_heritage_ids:[],short_description:'강화도 동막 갯벌에서 서해 일몰을 감상하는 투어다. 썰물 때 광활하게 펼쳐지는 갯벌 위로 붉은 해가 지는 장면이 압도적이며, 갯벌 위를 걸으며 일몰 사진을 찍는 명소다.',source_urls:['https://www.ganghwa.go.kr/'],data_confidence:'high',tags:['강화도','동막갯벌','서해낙조','인천','갯벌','일몰','강화'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'조석표 참고',phone:'032-934-7887'},
  {experience_id:'EX-JN-ISL-001',name:'완도 청산도 슬로 사이클링',category_main:'문화/체험',category_sub:'어드벤처/레포츠',region_main:'JN',region_sub:'전라남도 완도군',address:'전라남도 완도군 청산면 청산리 일원',lat:34.1958,lng:126.8681,price:'자전거 대여 1인 10,000원~',duration:'3~4시간',reservation_required:false,target_user:['개인','커플'],nearby_places:[],related_heritage_ids:[],short_description:'아시아 최초 슬로시티 청산도에서 전통 돌담길과 청보리밭을 자전거로 천천히 달리는 체험이다. 42km 슬로길 중 자전거 구간을 달리며 섬의 속도로 돌담·어촌·하늘을 감상한다.',source_urls:['https://www.wando.go.kr/'],data_confidence:'high',tags:['청산도','사이클링','완도','전남','슬로시티','자전거여행','돌담'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'연중 (자전거 대여: 09:00~17:00)',phone:'061-554-1501'},
  // 웰니스/힐링 체험
  {experience_id:'EX-GW-SPA-001',name:'평창 해피700 산림 치유 프로그램',category_main:'문화/체험',category_sub:'자연체험',region_main:'GW',region_sub:'강원특별자치도 평창군',address:'강원특별자치도 평창군 대관령면 솔봉로 325',lat:37.6596,lng:128.7150,price:'1인 20,000원~',duration:'2~3시간',reservation_required:true,target_user:['개인','커플'],nearby_places:[],related_heritage_ids:[],short_description:'해발 700m 평창 대관령에서 산림치유 전문가와 함께하는 산림 치유 프로그램이다. 피톤치드 가득한 소나무 숲에서 명상·숲 요가·허브 족욕을 체험하며 도시 스트레스를 해소하는 프리미엄 힐링 프로그램이다.',source_urls:['https://www.happy700.or.kr/'],data_confidence:'high',tags:['산림치유','평창','대관령','강원','힐링','피톤치드','숲명상'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~17:00',phone:'033-332-5765'},
  {experience_id:'EX-JJ-SPA-001',name:'제주 올레 명상 트레킹',category_main:'문화/체험',category_sub:'자연체험',region_main:'JJ',region_sub:'제주특별자치도 서귀포시',address:'제주특별자치도 서귀포시 성산읍 올레길 1코스 시작점',lat:33.3986,lng:126.9239,price:'무료',duration:'4~6시간',reservation_required:false,target_user:['개인','커플'],nearby_places:[],related_heritage_ids:[],short_description:'제주 올레길 1코스(시흥~광치기)를 명상하며 천천히 걷는 치유 여행이다. 성산일출봉을 바라보며 제주 해안을 따라 걷고, 걷는 동안 자연의 소리에 집중하는 마음챙김 걷기로 디지털 디톡스를 경험한다.',source_urls:['https://www.jejuolle.org/'],data_confidence:'high',tags:['제주올레','명상','트레킹','서귀포','마음챙김','힐링','성산일출봉'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'연중',phone:'064-762-2190'},
  // 전통 등 만들기
  {experience_id:'EX-CN-CRF-002',name:'서산 한지 연등 만들기',category_main:'문화/체험',category_sub:'전통공예',region_main:'CN',region_sub:'충청남도 서산시',address:'충청남도 서산시 운산면 마애삼존불길 65',lat:36.8038,lng:126.4603,price:'1인 15,000원',duration:'1~2시간',reservation_required:true,target_user:['가족','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'서산 마애삼존불 인근 공방에서 전통 한지로 연등을 만드는 체험이다. 대나무 틀에 한지를 붙이고 그림을 그려 나만의 등을 완성하며, 저녁에 불을 밝히면 은은한 빛이 퍼지는 감동을 경험한다.',source_urls:['https://www.seosan.go.kr/'],data_confidence:'high',tags:['연등만들기','한지공예','서산','충남','불교문화','전통공예','마애삼존불'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~17:00',phone:'041-660-2490'},
  // 해양 레포츠 추가
  {experience_id:'EX-JJ-SCU-001',name:'제주 스쿠버다이빙 체험',category_main:'문화/체험',category_sub:'해양 레포츠',region_main:'JJ',region_sub:'제주특별자치도 서귀포시',address:'제주특별자치도 서귀포시 성산읍 일출로 284-9 (섭지코지)',lat:33.4282,lng:126.9307,price:'1인 80,000원~',duration:'2~3시간',reservation_required:true,target_user:['개인','커플','청년'],nearby_places:[],related_heritage_ids:[],short_description:'제주 서귀포 앞바다에서 강사 동반 체험 다이빙으로 수심 5~8m 바닷속 세계를 탐험한다. 다이빙 자격증 없이도 강사와 함께 잠수해 형형색색 열대어와 산호초를 관찰하는 특별한 경험이다.',source_urls:['https://www.visitjeju.net/'],data_confidence:'high',tags:['스쿠버다이빙','제주','서귀포','다이빙체험','열대어','산호초','해양레포츠'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'09:00~17:00 (4~11월)',phone:'064-782-4300'},
  {experience_id:'EX-JN-OCN-003',name:'통영 카약 다도해 투어',category_main:'문화/체험',category_sub:'해양 레포츠',region_main:'JN',region_sub:'전라남도 여수시',address:'전라남도 여수시 돌산읍 향일암로 일원',lat:34.6539,lng:127.7547,price:'1인 50,000원~',duration:'3~4시간',reservation_required:true,target_user:['개인','커플'],nearby_places:[],related_heritage_ids:[],short_description:'여수 향일암 앞바다에서 카약을 타고 다도해 섬 사이를 탐방하는 해양 투어다. 섬과 섬 사이 좁은 해협을 카약으로 지나가는 특별한 경험으로 향일암 일출 카약 투어가 특히 유명하다.',source_urls:['https://www.yeosu.go.kr/'],data_confidence:'high',tags:['카약','여수','다도해','향일암','해양레포츠','섬투어','전남'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'05:00~17:00 (일출 투어 포함)',phone:'061-659-3745'},
  // 약선 음식 체험
  {experience_id:'EX-GJ-FUD-001',name:'광주 무등산 약초 비빔밥 체험',category_main:'문화/체험',category_sub:'발효/음식',region_main:'GJ',region_sub:'광주광역시 동구',address:'광주광역시 동구 무등로 일원',lat:35.1353,lng:127.0026,price:'1인 15,000원',duration:'2시간',reservation_required:true,target_user:['개인','가족'],nearby_places:[],related_heritage_ids:[],short_description:'무등산 자락에서 직접 채취한 약초·산나물로 광주 전통 약선 비빔밥을 만드는 체험이다. 무등산 도라지·취나물·고사리를 손질하고 조리해 먹으며, 광주의 맛 문화와 약초 이야기를 배운다.',source_urls:['https://www.gwangju.go.kr/tour/'],data_confidence:'high',tags:['약선비빔밥','무등산','광주','산나물','약초','전통음식','광주맛'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~16:00',phone:'062-226-3434'}
];

const exp = JSON.parse(fs.readFileSync(base+'data/experiences.json','utf8'));
const existingIds = new Set(exp.experiences.map(e=>e.experience_id));
const toAdd = newExps.filter(e=>!existingIds.has(e.experience_id));

exp.experiences.push(...toAdd);
exp.total = exp.experiences.length;
exp._updated = now;
fs.writeFileSync(base+'data/experiences.json', JSON.stringify(exp,null,2),'utf8');

const log = JSON.parse(fs.readFileSync(base+'logs/automation_log.json','utf8'));
log.runs.push({time:now, mode:'B', type:'체험학습', new_collected:toAdd.length, total_experiences:exp.total});
fs.writeFileSync(base+'logs/automation_log.json', JSON.stringify(log,null,2),'utf8');

console.log('체험 장소 추가:', toAdd.length+'개 / 총 체험', exp.total+'개');
toAdd.forEach(e=>console.log('  + ['+e.experience_id+']', e.name, '|', e.category_sub));
