const fs = require('fs');
const base = 'C:/Users/user/Desktop/클로드/gemkorea/';
const now = new Date().toISOString().slice(0,19);

const newExps = [
  // 제주 특화 체험
  {experience_id:'EX-JJ-NAT-002',name:'제주 오름 트레킹 (다랑쉬오름)',category_main:'문화/체험',category_sub:'자연체험',region_main:'JJ',region_sub:'제주특별자치도 제주시',address:'제주특별자치도 제주시 구좌읍 세화리 산6',lat:33.4628,lng:126.7919,price:'무료',duration:'1~2시간',reservation_required:false,target_user:['개인','커플','가족'],nearby_places:[],related_heritage_ids:[],short_description:'제주 동부 오름 중 가장 아름다운 분화구를 자랑하는 다랑쉬오름이다. 해발 382m 정상에서 내려다보는 완벽한 원형 분화구와 주변 오름 군락 파노라마가 압도적이며, 억새 피는 10~11월이 절정이다.',source_urls:['https://www.visitjeju.net/'],data_confidence:'high',tags:['다랑쉬오름','제주오름','분화구','트레킹','억새','구좌읍','제주'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'연중 (일출 전후 입산 제한)',phone:''},
  {experience_id:'EX-JJ-OCN-003',name:'제주 카약·패들보드 체험 (함덕)',category_main:'문화/체험',category_sub:'해양 레포츠',region_main:'JJ',region_sub:'제주특별자치도 제주시',address:'제주특별자치도 제주시 조천읍 함덕리 해변 일원',lat:33.5435,lng:126.6692,price:'1인 30,000원~',duration:'1~2시간',reservation_required:true,target_user:['개인','커플','청년'],nearby_places:[],related_heritage_ids:[],short_description:'함덕 서우봉 해변의 에메랄드 바다에서 카약과 스탠드업 패들보드를 즐기는 해양 레포츠 체험이다. 투명한 수심 1~2m 바닷속을 보며 패들링하는 색다른 경험을 할 수 있으며, 초보자 강습 프로그램도 운영된다.',source_urls:['https://www.visitjeju.net/'],data_confidence:'high',tags:['카약','패들보드','함덕','제주','해양레포츠','서우봉해변','여름여행'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'09:00~18:00 (5~10월)',phone:''},
  {experience_id:'EX-JJ-FES-001',name:'제주 정월대보름 들불축제',category_main:'문화/체험',category_sub:'축제',region_main:'JJ',region_sub:'제주특별자치도 제주시',address:'제주특별자치도 제주시 애월읍 봉성리 새별오름',lat:33.3889,lng:126.3608,price:'무료',duration:'3~5시간',reservation_required:false,target_user:['가족','개인','커플'],nearby_places:[],related_heritage_ids:[],short_description:'매년 음력 정월대보름 전후 새별오름에서 열리는 제주 전통 방목지 불 놓기 행사다. 수만 명이 모인 가운데 오름 전체가 화염에 휩싸이는 장관이 펼쳐지며, 전통 줄당기기·윷놀이·소싸움도 함께 즐길 수 있다.',source_urls:['https://www.jejufire.or.kr/'],data_confidence:'high',tags:['들불축제','제주','정월대보름','새별오름','불축제','제주전통','오름'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'annual',operating_hours:'음력 정월대보름 전후 (매년 2~3월)',phone:'064-728-2752'},
  // 전국 공방 체험
  {experience_id:'EX-GG-CRF-002',name:'양평 유리공예 체험',category_main:'문화/체험',category_sub:'도예/공방 체험',region_main:'GG',region_sub:'경기도 양평군',address:'경기도 양평군 서종면 북한강로 856',lat:37.5688,lng:127.4672,price:'1인 25,000원~',duration:'1~2시간',reservation_required:true,target_user:['커플','개인','가족'],nearby_places:[],related_heritage_ids:[],short_description:'북한강 뷰 앞에서 유리 블로잉(불기)을 직접 배우는 공예 체험이다. 1,200도 불꽃에서 유리를 녹여 파이프로 불어 컵·화병·소품을 만드는 과정을 체험하며 완성품을 가져간다.',source_urls:['https://www.yangpyeong.go.kr/'],data_confidence:'high',tags:['유리공예','양평','북한강','공방체험','경기','유리블로잉','커플체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~18:00',phone:'031-775-1234'},
  {experience_id:'EX-JN-CRF-002',name:'광양 매화마을 천연 향수 만들기',category_main:'문화/체험',category_sub:'전통공예',region_main:'JN',region_sub:'전라남도 광양시',address:'전라남도 광양시 다압면 매화길 일원',lat:35.0586,lng:127.7094,price:'1인 20,000원',duration:'1~2시간',reservation_required:true,target_user:['커플','개인','가족'],nearby_places:[],related_heritage_ids:[],short_description:'매년 3월 70만 그루의 매화가 피어나는 광양 매화마을에서 직접 채취한 매화꽃으로 천연 향수와 매화차를 만드는 체험이다. 매화 꽃잎 증류 과정을 체험하고 나만의 매화 향수 한 병을 가져갈 수 있다.',source_urls:['https://www.gwangyang.go.kr/'],data_confidence:'high',tags:['매화마을','광양','천연향수','매화체험','봄여행','전남','꽃체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'3월 매화 시즌 운영',phone:'061-797-2657'},
  // 지역 축제 추가
  {experience_id:'EX-GB-FES-002',name:'경주 신라 문화제',category_main:'문화/체험',category_sub:'축제',region_main:'GB',region_sub:'경상북도 경주시',address:'경상북도 경주시 첨성대 일원·월성 광장',lat:35.8347,lng:129.2194,price:'무료',duration:'1일',reservation_required:false,target_user:['가족','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'매년 10월 신라 천년의 역사를 재현하는 대한민국 최고 역사 문화 축제다. 신라대왕 행렬·화랑 퍼레이드·전통 혼례 재현·한지등 행렬이 첨성대·안압지 일원에서 펼쳐지며 야간 조명과 어우러져 더욱 화려하다.',source_urls:['https://www.silla.or.kr/'],data_confidence:'high',tags:['신라문화제','경주','신라','경북','역사축제','화랑','첨성대'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'annual',operating_hours:'매년 10월 (5~7일간)',phone:'054-779-6102'},
  {experience_id:'EX-CB-FES-001',name:'충주 세계 무술 축제',category_main:'문화/체험',category_sub:'축제',region_main:'CB',region_sub:'충청북도 충주시',address:'충청북도 충주시 탄금대공원 일원',lat:36.9816,lng:127.9358,price:'무료 (일부 유료)',duration:'3~5시간',reservation_required:false,target_user:['가족','개인'],nearby_places:[],related_heritage_ids:[],short_description:'매년 9~10월 세계 70여 개국 무술인이 참가하는 국제 무술 축제다. 태권도·택견·씨름·유도 등 한국 전통 무술 공연과 시범, 세계 무술 대련을 관람하고 직접 체험하는 프로그램이 진행된다.',source_urls:['https://www.martialarts.or.kr/'],data_confidence:'high',tags:['무술축제','충주','택견','태권도','세계무술','충북','국제축제'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'annual',operating_hours:'매년 9~10월 (10일간)',phone:'043-850-6731'},
  {experience_id:'EX-JN-FES-002',name:'여수 밤바다 낭만 포차 축제',category_main:'문화/체험',category_sub:'축제',region_main:'JN',region_sub:'전라남도 여수시',address:'전라남도 여수시 돌산읍 방죽포 해변 일원',lat:34.7340,lng:127.6977,price:'무료 입장 (먹거리 별도)',duration:'3~5시간',reservation_required:false,target_user:['커플','청년','개인'],nearby_places:[],related_heritage_ids:[],short_description:'여수 밤바다를 배경으로 해변 포차와 야시장이 열리는 낭만 축제다. 갓김치·서대회·돌게장 등 여수 특산 먹거리와 함께 버스킹·불꽃놀이·야경 유람선이 어우러지며 여수 밤바다 노래의 배경이 된 정박지를 밤에 걷는 특별한 경험이다.',source_urls:['https://www.yeosu.go.kr/'],data_confidence:'high',tags:['여수밤바다','포차축제','여수','전남','야시장','불꽃놀이','낭만여행'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'annual',operating_hours:'매년 8월 (2주간)',phone:'061-659-3745'},
  // 가족/어린이 체험 추가
  {experience_id:'EX-GG-KID-001',name:'용인 한국민속촌 전통 혼례',category_main:'문화/체험',category_sub:'어린이 체험',region_main:'GG',region_sub:'경기도 용인시',address:'경기도 용인시 기흥구 민속촌로 90',lat:37.2399,lng:127.1267,price:'성인 20,000원',duration:'3~5시간',reservation_required:false,target_user:['가족','어린이','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'조선 시대 민속 문화를 재현한 야외 박물관형 테마파크다. 900여 채 전통 한옥과 함께 전통 혼례·농악·줄타기 공연을 관람하고 조선 시대 의복 체험·전통 놀이(팽이·투호·윷)를 직접 즐길 수 있다.',source_urls:['https://www.koreanfolk.co.kr/'],data_confidence:'high',tags:['한국민속촌','용인','조선시대','한옥','전통문화','가족여행','경기'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:30~18:00 (연중무휴)',phone:'031-288-0000'},
  {experience_id:'EX-GG-KID-002',name:'과천 서울대공원',category_main:'문화/체험',category_sub:'어린이 체험',region_main:'GG',region_sub:'경기도 과천시',address:'경기도 과천시 막계동 대공원광장로 102',lat:37.4261,lng:126.9840,price:'동물원 성인 5,000원 (테마가든 별도)',duration:'3~5시간',reservation_required:false,target_user:['가족','어린이'],nearby_places:[],related_heritage_ids:[],short_description:'국내 최대 규모의 동물원과 식물원, 테마가든을 갖춘 복합 자연 체험 공원이다. 300여 종 3,700여 마리 동물과 함께 어린이동물원·야생동물원·동물 먹이 주기 체험을 운영하며 서울대공원 캠핑장도 갖추고 있다.',source_urls:['https://grandpark.seoul.go.kr/'],data_confidence:'high',tags:['서울대공원','과천','동물원','어린이','가족여행','경기','자연체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~19:00 (계절별 상이)',phone:'02-500-7335'},
  // 전통 발효/음식 체험 추가
  {experience_id:'EX-GW-FUD-002',name:'강릉 커피 로스팅 체험',category_main:'문화/체험',category_sub:'발효/음식',region_main:'GW',region_sub:'강원특별자치도 강릉시',address:'강원특별자치도 강릉시 창해로 307 (안목해변 커피거리)',lat:37.7695,lng:128.9469,price:'1인 15,000원~',duration:'1~2시간',reservation_required:true,target_user:['개인','커플'],nearby_places:[],related_heritage_ids:[],short_description:'대한민국 커피 도시 강릉에서 커피 생두 선별·로스팅·핸드드립까지 전 과정을 배우는 체험이다. 1980년대부터 시작된 강릉 안목 커피거리에서 바리스타 교관과 함께 나만의 블렌딩 원두를 만들어 집으로 가져간다.',source_urls:['https://www.gn.go.kr/'],data_confidence:'high',tags:['강릉커피','로스팅체험','안목해변','커피거리','강원','바리스타','핸드드립'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~20:00',phone:''},
  {experience_id:'EX-JB-FUD-001',name:'전주 전통 비빔밥 만들기 체험',category_main:'문화/체험',category_sub:'발효/음식',region_main:'JB',region_sub:'전라북도 전주시',address:'전라북도 전주시 완산구 전동 3가 94',lat:35.8158,lng:127.1542,price:'1인 20,000원',duration:'1~2시간',reservation_required:true,target_user:['가족','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'전주 한옥마을 내 전통 요리 교실에서 전주비빔밥의 핵심인 육회·고추장·30가지 나물을 직접 준비하고 만들어 먹는 체험이다. 조선 왕실에 올린 비빔밥 레시피의 역사와 의미를 배우고 완성 후 시식한다.',source_urls:['https://www.jeonju.go.kr/'],data_confidence:'high',tags:['전주비빔밥','한옥마을','전주','전북','요리체험','한식','외국인체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~17:00',phone:'063-282-1330'},
  {experience_id:'EX-GN-FUD-001',name:'통영 굴 까기 체험',category_main:'문화/체험',category_sub:'발효/음식',region_main:'GN',region_sub:'경상남도 통영시',address:'경상남도 통영시 도남동 항구 일원',lat:34.8465,lng:128.4348,price:'1인 10,000원~',duration:'1~2시간',reservation_required:false,target_user:['가족','개인'],nearby_places:[],related_heritage_ids:[],short_description:'국내 굴 생산량 80%를 차지하는 통영에서 굴 양식장을 방문하고 굴 까기를 직접 체험하는 프로그램이다. 갓 수확한 생굴과 굴구이를 현장에서 먹으며 통영 어민의 삶과 굴 양식 문화를 이해하는 시간이다.',source_urls:['https://www.tongyeong.go.kr/'],data_confidence:'high',tags:['굴체험','통영','경남','굴까기','어촌체험','통영굴','해산물'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'11~4월 굴 시즌 운영',phone:'055-650-4681'}
];

const exp = JSON.parse(fs.readFileSync(base+'data/experiences.json','utf8'));
const existingIds = new Set(exp.experiences.map(e=>e.experience_id));
const toAdd = newExps.filter(e=>!existingIds.has(e.experience_id));

exp.experiences.push(...toAdd);
exp.total = exp.experiences.length;
exp._updated = now;
fs.writeFileSync(base+'data/experiences.json', JSON.stringify(exp,null,2),'utf8');

const log = JSON.parse(fs.readFileSync(base+'logs/automation_log.json','utf8'));
log.runs.push({time:now, mode:'B', type:'체험학습', new_collected:toAdd.length, total_experiences:exp.total});
fs.writeFileSync(base+'logs/automation_log.json', JSON.stringify(log,null,2),'utf8');

console.log('체험 장소 추가:', toAdd.length+'개 / 총 체험', exp.total+'개');
toAdd.forEach(e=>console.log('  + ['+e.experience_id+']', e.name, '|', e.category_sub));
