const fs = require('fs');
const base = 'C:/Users/user/Desktop/클로드/gemkorea/';
const now = new Date().toISOString().slice(0,19);

const newExps = [
  // 전통 음식 체험 추가
  {experience_id:'EX-BS-FUD-001',name:'부산 기장 미역·다시마 채취 체험',category_main:'문화/체험',category_sub:'해양체험',region_main:'BS',region_sub:'부산광역시 기장군',address:'부산광역시 기장군 기장읍 기장해안로 일원',lat:35.2401,lng:129.2195,price:'1인 15,000원',duration:'2시간',reservation_required:true,target_user:['가족','개인'],nearby_places:[],related_heritage_ids:[],short_description:'동해안 청정 해역 기장에서 어민과 함께 미역과 다시마를 직접 채취하고 손질하는 어촌 체험이다. 봄철 생미역 채취·건조 과정을 배우고 갓 딴 미역으로 미역국을 끓여 먹는 특별한 경험이다.',source_urls:['https://www.gijang.go.kr/'],data_confidence:'high',tags:['기장','미역체험','부산','어촌체험','생미역','해양체험','다시마'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'3~5월 미역 시즌',phone:'051-709-4000'},
  {experience_id:'EX-GW-FRM-002',name:'홍천 곤드레 나물 채취 체험',category_main:'문화/체험',category_sub:'농촌 체험',region_main:'GW',region_sub:'강원특별자치도 홍천군',address:'강원특별자치도 홍천군 내촌면 와야리 일원',lat:37.7253,lng:128.1419,price:'1인 10,000원~',duration:'2~3시간',reservation_required:true,target_user:['가족','개인'],nearby_places:[],related_heritage_ids:[],short_description:'강원도 대표 산나물 곤드레를 직접 채취하고 곤드레밥을 지어 먹는 농촌 체험이다. 5~6월 산나물 채취 시즌에 운영하며 곤드레 된장찌개·묵나물 만들기를 함께 배울 수 있다.',source_urls:['https://www.hongcheon.go.kr/'],data_confidence:'high',tags:['곤드레','홍천','강원','나물채취','산나물','농촌체험','강원도밥상'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'5~6월 나물 시즌',phone:'033-430-2704'},
  // 역사 체험 추가
  {experience_id:'EX-GG-HST-001',name:'수원 화성 성곽 야경 투어',category_main:'문화/체험',category_sub:'역사 체험',region_main:'GG',region_sub:'경기도 수원시',address:'경기도 수원시 팔달구 매산로2가 16',lat:37.2790,lng:126.9931,price:'야간 성곽 투어 1인 5,000원',duration:'2시간',reservation_required:true,target_user:['커플','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'유네스코 세계문화유산 수원화성 5.7km 성곽을 야간에 걷는 투어다. 서장대·동북공심돈·방화수류정 등 주요 건축물이 조명을 받아 낮과 전혀 다른 분위기를 연출한다. 정조대왕의 효심이 담긴 화성의 밤 이야기를 해설사와 함께 듣는다.',source_urls:['https://www.swcf.or.kr/'],data_confidence:'high',tags:['수원화성','야경투어','유네스코','수원','경기','정조대왕','성곽야경'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'야간 투어: 4~10월 (금·토 운영)',phone:'031-290-3600'},
  {experience_id:'EX-CB-HST-001',name:'공주 무령왕릉 VR 체험',category_main:'문화/체험',category_sub:'역사 체험',region_main:'CB',region_sub:'충청남도 공주시',address:'충청남도 공주시 왕릉로 37-2',lat:36.4556,lng:127.1202,price:'VR 체험 1인 5,000원',duration:'1~2시간',reservation_required:false,target_user:['가족','어린이','개인'],nearby_places:[],related_heritage_ids:[],short_description:'백제 무령왕릉 국립공주박물관에서 VR로 왕릉 내부를 탐험하는 역사 체험이다. 1971년 발굴 당시 금제관식·금귀걸이 등 4,600점의 유물이 완전한 상태로 발견된 무령왕릉을 가상현실로 직접 들어가 볼 수 있다.',source_urls:['https://gongju.museum.go.kr/'],data_confidence:'high',tags:['무령왕릉','VR체험','공주','백제','충남','왕릉체험','역사교육'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~18:00 (월요일 휴관)',phone:'041-850-6300'},
  {experience_id:'EX-GW-HST-001',name:'철원 DMZ 비무장지대 탐방',category_main:'문화/체험',category_sub:'역사 체험',region_main:'GW',region_sub:'강원특별자치도 철원군',address:'강원특별자치도 철원군 동송읍 이평리 일원',lat:38.2714,lng:127.3146,price:'1인 15,000원~',duration:'3~4시간',reservation_required:true,target_user:['개인','커플','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'한국 전쟁 격전지이자 세계 유일의 분단 현장 철원 DMZ를 탐방하는 역사 체험 투어다. 두루미 서식지로도 유명한 철원평야와 노동당사·백마고지 전적지·제2땅굴을 방문하며 한반도 분단의 현실을 체험한다.',source_urls:['https://www.cwg.go.kr/tour/'],data_confidence:'high',tags:['DMZ','철원','비무장지대','한국전쟁','분단','강원','두루미','노동당사'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~16:00 (사전 예약 필수)',phone:'033-450-5558'},
  // 창작/공방 체험
  {experience_id:'EX-SE-CRF-002',name:'성수동 가죽 공방 체험',category_main:'문화/체험',category_sub:'도예/공방 체험',region_main:'SE',region_sub:'서울특별시 성동구',address:'서울특별시 성동구 성수이로7가길 일원',lat:37.5444,lng:127.0558,price:'1인 35,000원~',duration:'2~3시간',reservation_required:true,target_user:['커플','개인','청년'],nearby_places:[],related_heritage_ids:[],short_description:'한국 가죽 공예의 발상지 성수동에서 직접 가죽 지갑·카드지갑·명함집을 만드는 공방 체험이다. 재봉틀·가죽 도구를 사용해 나만의 소품을 완성하고 레이저 각인으로 이름이나 문구를 새겨 가져간다.',source_urls:['https://www.seongdong.go.kr/'],data_confidence:'high',tags:['성수동','가죽공방','서울','공방체험','가죽지갑','핸드메이드','성동구'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~21:00',phone:''},
  {experience_id:'EX-GG-CRF-003',name:'파주 캔들·비누 공방 체험',category_main:'문화/체험',category_sub:'도예/공방 체험',region_main:'GG',region_sub:'경기도 파주시',address:'경기도 파주시 탄현면 헤이리마을길 93-119 (헤이리 예술마을)',lat:37.7374,lng:126.7224,price:'1인 20,000원~',duration:'1~2시간',reservation_required:true,target_user:['커플','개인'],nearby_places:[],related_heritage_ids:[],short_description:'파주 헤이리 예술마을 내 공방에서 천연 소이캔들과 천연 비누를 직접 만드는 체험이다. 향 조합·색상 선택·용기 디자인을 모두 직접 결정해 나만의 작품을 완성하며, 헤이리 갤러리 투어와 함께 반나절 코스로 즐길 수 있다.',source_urls:['https://www.heyri.net/'],data_confidence:'high',tags:['헤이리','파주','캔들','비누','공방체험','경기','예술마을','커플'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~18:00',phone:'031-946-8551'},
  // 문화예술 체험
  {experience_id:'EX-SE-ART-004',name:'인사동 전통 풍물놀이 체험',category_main:'문화/체험',category_sub:'문화예술',region_main:'SE',region_sub:'서울특별시 종로구',address:'서울특별시 종로구 인사동길 일원',lat:37.5742,lng:126.9853,price:'1인 10,000원~',duration:'1시간',reservation_required:false,target_user:['가족','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'인사동 전통문화 체험 공간에서 농악대 악기(꽹과리·장구·북·소고)를 배우고 직접 풍물놀이 리듬을 익히는 체험이다. 외국인 관광객을 위한 영어 해설 프로그램도 운영되며 한국 전통 음악의 흥을 직접 느낄 수 있다.',source_urls:['https://www.insadong.info/'],data_confidence:'high',tags:['풍물놀이','인사동','농악','서울','전통문화','외국인체험','꽹과리'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~18:00',phone:''},
  {experience_id:'EX-DG-ART-001',name:'대구 근대 골목 투어',category_main:'문화/체험',category_sub:'역사 체험',region_main:'DG',region_sub:'대구광역시 중구',address:'대구광역시 중구 계산동2가 71 (계산성당 앞)',lat:35.8681,lng:128.5922,price:'해설 투어 1인 5,000원 (자유 탐방 무료)',duration:'2~3시간',reservation_required:false,target_user:['개인','커플','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'일제강점기 대구의 모습이 그대로 보존된 계산동·약전골목·3·1만세운동길 등을 걷는 근대 역사 투어다. 이상화·서상돈 등 독립운동가의 자취와 1900년대 초 상권 골목을 해설사와 함께 탐방할 수 있다.',source_urls:['https://www.daeguculture.or.kr/'],data_confidence:'high',tags:['대구근대골목','계산동','약전골목','대구','독립운동','근대역사','중구'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'연중 (해설 투어: 화~일 10시·14시)',phone:'053-661-3326'},
  // 제주 추가 체험
  {experience_id:'EX-JJ-CRF-001',name:'제주 옹기 항아리 만들기 체험',category_main:'문화/체험',category_sub:'전통공예',region_main:'JJ',region_sub:'제주특별자치도 제주시',address:'제주특별자치도 제주시 한경면 저지리 예술인마을 일원',lat:33.3297,lng:126.2041,price:'1인 25,000원',duration:'1~2시간',reservation_required:true,target_user:['커플','개인','가족'],nearby_places:[],related_heritage_ids:[],short_description:'제주 저지리 예술인마을 공방에서 제주 전통 옹기 항아리와 허벅(제주 전통 물허벅)을 직접 빚는 체험이다. 제주 흑토를 사용해 물레 성형·표면 문양 새기기를 체험하고 소성 후 완성품을 택배로 받는다.',source_urls:['https://www.visitjeju.net/'],data_confidence:'high',tags:['제주옹기','허벅','전통공예','저지리','제주','도예체험','예술인마을'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~17:00',phone:'064-772-3100'},
  {experience_id:'EX-JJ-HST-001',name:'제주 4·3 역사 탐방 투어',category_main:'문화/체험',category_sub:'역사 체험',region_main:'JJ',region_sub:'제주특별자치도 제주시',address:'제주특별자치도 제주시 명림로 430 (4·3 평화공원)',lat:33.4917,lng:126.5628,price:'무료 (해설 사전 신청)',duration:'2~3시간',reservation_required:true,target_user:['개인','청년'],nearby_places:[],related_heritage_ids:[],short_description:'1948년 제주 4·3 사건의 역사를 기억하는 평화공원과 북촌 너분숭이 현장을 탐방하는 추모 역사 투어다. 4·3 평화기념관 전시와 해설사 동반 탐방을 통해 한국 현대사의 비극적 사건을 이해하고 평화의 의미를 되새긴다.',source_urls:['https://www.jeju43peace.or.kr/'],data_confidence:'high',tags:['제주4·3','평화공원','역사투어','제주','현대사','추모','북촌'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~18:00 (월요일 휴관)',phone:'064-723-4301'},
  // 남해안 특색 체험
  {experience_id:'EX-GN-VIL-003',name:'거제 포로수용소 역사 투어',category_main:'문화/체험',category_sub:'역사 체험',region_main:'GN',region_sub:'경상남도 거제시',address:'경상남도 거제시 계룡로 61',lat:34.8804,lng:128.6201,price:'성인 9,000원',duration:'1~2시간',reservation_required:false,target_user:['가족','개인'],nearby_places:[],related_heritage_ids:[],short_description:'6·25 전쟁 당시 UN군이 운영하던 거제 포로수용소 유적을 체험형 전시로 관람하는 역사 투어다. 실물 크기 막사 복원·포로 생활 재현·영상 체험관을 통해 한국 전쟁의 국제적 맥락을 이해한다.',source_urls:['https://www.geojedpow.com/'],data_confidence:'high',tags:['거제포로수용소','거제','6·25전쟁','경남','역사체험','전쟁유적','한국전쟁'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~18:00 (연중무휴)',phone:'055-639-6615'},
  {experience_id:'EX-JN-VIL-001',name:'여수 돌산도 갓김치 담그기',category_main:'문화/체험',category_sub:'발효/음식',region_main:'JN',region_sub:'전라남도 여수시',address:'전라남도 여수시 돌산읍 계동리 갓김치마을',lat:34.6871,lng:127.7289,price:'1인 15,000원',duration:'2시간',reservation_required:true,target_user:['가족','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'여수 돌산도 특산품 돌산갓으로 갓김치를 직접 담그는 체험이다. 돌산갓의 매콤·알싸한 특성과 갓김치 양념 배합 비율을 배우고 직접 버무린 갓김치를 용기에 담아 가져간다.',source_urls:['https://www.yeosu.go.kr/'],data_confidence:'high',tags:['갓김치','돌산도','여수','전남','발효음식','김치체험','돌산갓'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~16:00',phone:'061-659-3745'}
];

const exp = JSON.parse(fs.readFileSync(base+'data/experiences.json','utf8'));
const existingIds = new Set(exp.experiences.map(e=>e.experience_id));
const toAdd = newExps.filter(e=>!existingIds.has(e.experience_id));

exp.experiences.push(...toAdd);
exp.total = exp.experiences.length;
exp._updated = now;
fs.writeFileSync(base+'data/experiences.json', JSON.stringify(exp,null,2),'utf8');

const log = JSON.parse(fs.readFileSync(base+'logs/automation_log.json','utf8'));
log.runs.push({time:now, mode:'B', type:'체험학습', new_collected:toAdd.length, total_experiences:exp.total});
fs.writeFileSync(base+'logs/automation_log.json', JSON.stringify(log,null,2),'utf8');

console.log('체험 장소 추가:', toAdd.length+'개 / 총 체험', exp.total+'개');
toAdd.forEach(e=>console.log('  + ['+e.experience_id+']', e.name, '|', e.category_sub));
