const fs = require('fs');
const base = 'C:/Users/user/Desktop/클로드/gemkorea/';
const now = new Date().toISOString().slice(0,19);

const newExps = [
  // 테마파크
  {experience_id:'EX-GG-FAM-002',name:'에버랜드',category_main:'문화/체험',category_sub:'테마파크',region_main:'GG',region_sub:'경기도 용인시',address:'경기도 용인시 처인구 포곡읍 에버랜드로 199',lat:37.2952,lng:127.2025,price:'성인 62,000원 (온라인 할인 가능)',duration:'6~10시간',reservation_required:false,target_user:['가족','어린이','커플'],nearby_places:[],related_heritage_ids:[],short_description:'국내 최대 면적의 복합 테마파크로 4개 테마존에 40여 가지 어트랙션을 갖추고 있다. 봄 튤립·여름 장미·가을 핼러윈·겨울 빛 축제 등 계절별 대형 이벤트가 열리며 사파리월드와 워터파크 캐리비안베이도 인접해 있다.',source_urls:['https://www.everland.com/'],data_confidence:'high',tags:['에버랜드','테마파크','용인','경기','어트랙션','계절축제','가족여행'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~22:00 (시즌별 상이)',phone:'031-320-5000'},
  {experience_id:'EX-SE-FAM-001',name:'롯데월드 어드벤처',category_main:'문화/체험',category_sub:'테마파크',region_main:'SE',region_sub:'서울특별시 송파구',address:'서울특별시 송파구 올림픽로 240',lat:37.5111,lng:127.0983,price:'성인 62,000원 (온라인 할인 가능)',duration:'4~8시간',reservation_required:false,target_user:['가족','어린이','커플'],nearby_places:[],related_heritage_ids:[],short_description:'세계 최대 규모의 실내 테마파크를 포함한 복합 놀이공원이다. 실내 어드벤처와 야외 매직아일랜드로 구성되어 날씨에 상관없이 즐길 수 있으며 잠실 석촌호수와 인접해 봄 벚꽃 시즌이 특히 아름답다.',source_urls:['https://adventure.lotteworld.com/'],data_confidence:'high',tags:['롯데월드','테마파크','서울','잠실','실내놀이공원','석촌호수','가족여행'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:30~22:00 (금·토·일 23:00)',phone:'02-411-2000'},
  {experience_id:'EX-GB-FAM-001',name:'경주월드',category_main:'문화/체험',category_sub:'테마파크',region_main:'GB',region_sub:'경상북도 경주시',address:'경상북도 경주시 보문로 544',lat:37.2952,lng:129.2625,price:'성인 42,000원',duration:'4~8시간',reservation_required:false,target_user:['가족','어린이','커플'],nearby_places:[],related_heritage_ids:[],short_description:'신라 천년 고도 경주 보문관광단지 내에 위치한 테마파크다. 어트랙션과 함께 캘리포니아비치 워터파크를 함께 운영하며, 불국사·석굴암·동궁과 월지 등 세계문화유산 관광과 연계할 수 있는 특별한 위치에 있다.',source_urls:['https://www.gjworld.com/'],data_confidence:'high',tags:['경주월드','테마파크','경주','경북','보문단지','워터파크','신라문화'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~18:00 (시즌·요일별 상이)',phone:'054-740-2000'},
  {experience_id:'EX-JJ-FAM-001',name:'제주 신화테마파크',category_main:'문화/체험',category_sub:'테마파크',region_main:'JJ',region_sub:'제주특별자치도 서귀포시',address:'제주특별자치도 서귀포시 안덕면 신화역사로 304번길 38',lat:33.3097,lng:126.2680,price:'성인 37,000원',duration:'4~8시간',reservation_required:false,target_user:['가족','어린이','커플'],nearby_places:[],related_heritage_ids:[],short_description:'2017년 개장한 제주 최대 복합 리조트형 테마파크다. 신화·어드벤처랜드와 워터파크, 카지노, 5성급 호텔이 한 단지에 있으며 한국·중국·서양 신화를 테마로 한 독특한 어트랙션이 특징이다.',source_urls:['https://www.shinhwaworld.com/'],data_confidence:'high',tags:['신화테마파크','제주','테마파크','서귀포','리조트','워터파크'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~20:00 (시즌별 상이)',phone:'064-908-8000'},
  {experience_id:'EX-GN-FAM-001',name:'통도환타지아',category_main:'문화/체험',category_sub:'테마파크',region_main:'GN',region_sub:'경상남도 양산시',address:'경상남도 양산시 하북면 통도로 1218',lat:35.4467,lng:129.0431,price:'성인 37,000원',duration:'4~8시간',reservation_required:false,target_user:['가족','어린이'],nearby_places:[],related_heritage_ids:[],short_description:'영남권 대표 테마파크로 1984년 개장해 40년 역사를 자랑한다. 롤러코스터·바이킹·자이로드롭 등 30여 가지 어트랙션과 함께 통도사, 홍룡폭포 등 인근 자연경관과 묶어 가족 여행 코스로 즐기기 좋다.',source_urls:['https://www.fantasia.co.kr/'],data_confidence:'high',tags:['통도환타지아','양산','테마파크','경남','영남권','가족여행'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:30~18:00 (성수기 연장)',phone:'055-350-5000'},
  // 워터파크
  {experience_id:'EX-GG-WAT-001',name:'캐리비안베이 워터파크',category_main:'문화/체험',category_sub:'워터파크',region_main:'GG',region_sub:'경기도 용인시',address:'경기도 용인시 처인구 포곡읍 에버랜드로 199',lat:37.2918,lng:127.2003,price:'성인 55,000원 (시즌별 상이)',duration:'4~8시간',reservation_required:false,target_user:['가족','어린이','커플'],nearby_places:[],related_heritage_ids:[],short_description:'아시아 최대 규모의 워터파크로 에버랜드와 인접해 있다. 실내 스파와 야외 풀을 결합한 형태로 파도풀·워터슬라이드·유수풀 등 다양한 시설을 갖추고 있어 여름철 대표 피서지로 꼽힌다.',source_urls:['https://www.everland.com/caribbean/'],data_confidence:'high',tags:['캐리비안베이','워터파크','용인','경기','여름피서','물놀이','에버랜드'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'10:00~20:00 (하계 운영, 실내관 연중)',phone:'031-320-5000'},
  {experience_id:'EX-GW-WAT-001',name:'오션월드 워터파크',category_main:'문화/체험',category_sub:'워터파크',region_main:'GW',region_sub:'강원특별자치도 홍천군',address:'강원특별자치도 홍천군 서면 한치골길 262',lat:37.6832,lng:127.9211,price:'성인 60,000원 (시즌별 상이)',duration:'4~8시간',reservation_required:false,target_user:['가족','어린이','커플'],nearby_places:[],related_heritage_ids:[],short_description:'강원도 홍천의 피닉스 파크 리조트 내 워터파크로 아시아 최대 규모의 인공 파도풀을 자랑한다. 지하 온천수를 활용한 스파시설과 각종 워터슬라이드, 어린이 전용 수영장을 갖추고 있다.',source_urls:['https://www.phoenixhnc.com/oceanworld/'],data_confidence:'high',tags:['오션월드','홍천','강원','워터파크','여름피서','인공파도풀','리조트'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'10:00~18:00 (하계 운영)',phone:'033-440-6000'},
  // 스키장
  {experience_id:'EX-GW-SKI-001',name:'용평리조트 스키장',category_main:'문화/체험',category_sub:'스키/겨울 레포츠',region_main:'GW',region_sub:'강원특별자치도 평창군',address:'강원특별자치도 평창군 대관령면 올림픽로 715',lat:37.6662,lng:128.6927,price:'리프트권 성인 65,000원~',duration:'4~8시간',reservation_required:false,target_user:['가족','어린이','커플','개인'],nearby_places:[],related_heritage_ids:[],short_description:'1975년 개장한 국내 최초 대규모 스키장으로 2018 평창동계올림픽 알파인스키 경기장이다. 31개 슬로프와 15개 리프트를 갖추고 있으며 초보자부터 전문가까지 모든 레벨의 코스가 마련되어 있다.',source_urls:['https://www.yongpyong.co.kr/'],data_confidence:'high',tags:['용평리조트','스키장','평창','강원','평창올림픽','대관령','겨울여행'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'08:30~22:00 (야간 스키)',phone:'033-335-5757'},
  {experience_id:'EX-GW-SKI-002',name:'하이원리조트 스키장',category_main:'문화/체험',category_sub:'스키/겨울 레포츠',region_main:'GW',region_sub:'강원특별자치도 정선군',address:'강원특별자치도 정선군 고한읍 하이원길 424',lat:37.2197,lng:128.8592,price:'리프트권 성인 68,000원~',duration:'4~8시간',reservation_required:false,target_user:['가족','어린이','커플','개인'],nearby_places:[],related_heritage_ids:[],short_description:'해발 1,340m 고지에 위치한 강원도 대표 스키 리조트다. 최장 5.8km 슬로프를 포함한 27개 코스와 전국 최대 규모의 곤돌라를 갖추고 있으며 야간 스키와 눈썰매장을 함께 운영한다.',source_urls:['https://www.high1.com/'],data_confidence:'high',tags:['하이원리조트','스키장','정선','강원','겨울여행','고한','눈썰매'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'08:30~22:00 (야간)',phone:'1588-7789'},
  {experience_id:'EX-JB-SKI-001',name:'무주리조트 스키장',category_main:'문화/체험',category_sub:'스키/겨울 레포츠',region_main:'JB',region_sub:'전라북도 무주군',address:'전라북도 무주군 설천면 만선로 185',lat:35.8986,lng:127.6578,price:'리프트권 성인 60,000원~',duration:'4~8시간',reservation_required:false,target_user:['가족','어린이','커플','개인'],nearby_places:[],related_heritage_ids:[],short_description:'덕유산 국립공원 품에 안긴 남부권 최대 스키 리조트다. 천혜의 자연 속 22개 슬로프와 야간 스키, 눈썰매장을 갖추고 있으며 곤돌라를 타고 덕유산 정상 향적봉(1,614m) 설경을 감상할 수 있다.',source_urls:['https://www.mujuresort.com/'],data_confidence:'high',tags:['무주리조트','스키장','무주','전북','덕유산','남부스키','겨울여행'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'08:30~21:00',phone:'063-322-9000'},
  // 해양 레포츠
  {experience_id:'EX-GW-SRF-001',name:'양양 서핑 체험',category_main:'문화/체험',category_sub:'해양 레포츠',region_main:'GW',region_sub:'강원특별자치도 양양군',address:'강원특별자치도 양양군 현남면 인구리 해변 일원',lat:38.0783,lng:128.7112,price:'입문 강습 1인 50,000원~',duration:'2~3시간',reservation_required:true,target_user:['개인','커플','청년'],nearby_places:[],related_heritage_ids:[],short_description:'동해안 최고의 서핑 명소로 수도권에서 2시간 거리의 접근성 덕에 연간 100만 명 이상이 찾는 서핑 성지다. 인구해변을 중심으로 수십 개의 서핑 스쿨이 운영되며 초보자 입문 강습부터 프리 서핑까지 즐길 수 있다.',source_urls:['https://www.yangyang.go.kr/tour/'],data_confidence:'high',tags:['서핑','양양','강원','동해','인구해변','해양레포츠','여름여행'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'상시 (성수기 4~10월)',phone:''},
  {experience_id:'EX-JJ-OCN-002',name:'서귀포 잠수함 체험',category_main:'문화/체험',category_sub:'해양체험',region_main:'JJ',region_sub:'제주특별자치도 서귀포시',address:'제주특별자치도 서귀포시 칠십리로 156-1',lat:33.2456,lng:126.5636,price:'성인 74,000원',duration:'1시간 30분',reservation_required:true,target_user:['가족','어린이','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'서귀포 바닷속 30~40m 깊이까지 내려가 제주 열대어와 산호초를 유리창 너머로 감상하는 잠수함 체험이다. 별도의 수영 기술 없이도 탑승 가능하며 운항 시간은 약 45분이다.',source_urls:['https://www.submarines.co.kr/'],data_confidence:'high',tags:['잠수함','서귀포','제주','바닷속','산호초','해양체험','가족여행'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~17:00',phone:'064-732-6060'},
  // 과학관/박물관
  {experience_id:'EX-DJ-MUS-001',name:'국립중앙과학관',category_main:'문화/체험',category_sub:'과학관',region_main:'DJ',region_sub:'대전광역시 유성구',address:'대전광역시 유성구 대덕대로 481',lat:36.3718,lng:127.3672,price:'무료 (일부 유료 전시)',duration:'2~4시간',reservation_required:false,target_user:['가족','어린이','개인'],nearby_places:[],related_heritage_ids:[],short_description:'국내 최대 규모의 과학 전시·체험 기관으로 상설 전시관과 자연사관, 천체관, 생물탐구관 등 다양한 시설을 운영한다. 공룡 화석·우주 탐험·첨단 과학 체험 등 어린이와 학생을 위한 교육 프로그램이 풍부하다.',source_urls:['https://www.science.go.kr/'],data_confidence:'high',tags:['국립중앙과학관','대전','과학체험','교육여행','어린이','공룡','천체'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:30~17:30 (월요일 휴관)',phone:'042-601-7894'},
  {experience_id:'EX-BS-MUS-002',name:'국립해양박물관',category_main:'문화/체험',category_sub:'박물관',region_main:'BS',region_sub:'부산광역시 영도구',address:'부산광역시 영도구 해양로 301번길 45',lat:35.0702,lng:129.0683,price:'무료',duration:'2~3시간',reservation_required:false,target_user:['가족','어린이','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'우리나라 유일의 국립 해양 전문 박물관으로 해양 역사·문화·과학·산업을 아우르는 전시가 펼쳐진다. 옥포해전 모형·해양 탐험 체험관·수족관을 갖추고 있으며 부산항과 영도 앞바다 전망이 일품이다.',source_urls:['https://www.knmm.or.kr/'],data_confidence:'high',tags:['국립해양박물관','부산','영도','해양문화','수족관','어린이체험','부산항'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~18:00 (월요일 휴관)',phone:'051-309-1900'},
  {experience_id:'EX-GG-MUS-002',name:'국립과천과학관',category_main:'문화/체험',category_sub:'과학관',region_main:'GG',region_sub:'경기도 과천시',address:'경기도 과천시 상하벌로 110',lat:37.4272,lng:126.9886,price:'성인 4,000원',duration:'2~4시간',reservation_required:false,target_user:['가족','어린이','개인'],nearby_places:[],related_heritage_ids:[],short_description:'서울 근교 대표 가족 나들이 명소로 최첨단 과학기술 체험 전시와 천체투영관, 인터랙티브 과학 놀이터를 운영한다. 상상홀 대형 공룡 로봇과 4D영상관이 특히 어린이들에게 인기가 높다.',source_urls:['https://www.sciencecenter.go.kr/'],data_confidence:'high',tags:['국립과천과학관','과천','경기','과학체험','어린이','천체투영관','서울근교'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:30~17:30 (월요일 휴관)',phone:'02-3677-1500'}
];

const exp = JSON.parse(fs.readFileSync(base+'data/experiences.json','utf8'));
const existingIds = new Set(exp.experiences.map(e=>e.experience_id));
const toAdd = newExps.filter(e=>!existingIds.has(e.experience_id));

exp.experiences.push(...toAdd);
exp.total = exp.experiences.length;
exp._updated = now;
fs.writeFileSync(base+'data/experiences.json', JSON.stringify(exp,null,2),'utf8');

// automation_log 기록
const log = JSON.parse(fs.readFileSync(base+'logs/automation_log.json','utf8'));
log.runs.push({time:now, mode:'B', type:'체험학습', new_collected:toAdd.length, total_experiences:exp.total});
fs.writeFileSync(base+'logs/automation_log.json', JSON.stringify(log,null,2),'utf8');

console.log('체험 장소 추가:', toAdd.length+'개 / 총 체험', exp.total+'개');
toAdd.forEach(e=>console.log('  + ['+e.experience_id+']', e.name, '|', e.category_sub));
