const fs = require('fs');
const base = 'C:/Users/user/Desktop/클로드/gemkorea/';
const now = new Date().toISOString().slice(0,19);

const newExps = [
  // 농촌/생태 체험마을
  {experience_id:'EX-JB-VIL-001',name:'임실치즈마을',category_main:'문화/체험',category_sub:'농촌 체험',region_main:'JB',region_sub:'전라북도 임실군',address:'전라북도 임실군 임실읍 치즈마을로 2',lat:35.6163,lng:127.2794,price:'체험 프로그램 1인 12,000원~',duration:'2~3시간',reservation_required:true,target_user:['가족','어린이'],nearby_places:[],related_heritage_ids:[],short_description:'1967년 지정환 신부가 시작한 국내 첫 치즈 제조지에서 운영하는 농촌 체험 마을이다. 치즈 만들기·피자 만들기·양젖 짜기 등 유제품 전 과정을 체험할 수 있으며 가족 단위 어린이 농촌 교육 프로그램이 풍부하다.',source_urls:['https://www.cheesemaul.com/'],data_confidence:'high',tags:['임실치즈마을','치즈체험','임실','전북','농촌체험','피자만들기','어린이체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~17:00',phone:'063-643-3700'},
  {experience_id:'EX-GN-VIL-002',name:'산청 지리산 한방 약초 체험',category_main:'문화/체험',category_sub:'농촌 체험',region_main:'GN',region_sub:'경상남도 산청군',address:'경상남도 산청군 산청읍 동의보감로 555',lat:35.4136,lng:127.8734,price:'체험 1인 10,000원~',duration:'2시간',reservation_required:true,target_user:['가족','개인'],nearby_places:[],related_heritage_ids:[],short_description:'동의보감 한방 테마파크 내 약초 채취·한방차 만들기·약재 탕전 체험을 운영한다. 지리산 청정 자연 속 진귀한 약초를 직접 관찰하고 허준의 동의보감을 테마로 한 한의학 체험관을 함께 둘러볼 수 있다.',source_urls:['https://www.donguibogam.or.kr/'],data_confidence:'high',tags:['동의보감','한방체험','약초','산청','지리산','한의학','경남'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~18:00 (월요일 휴관)',phone:'055-970-8762'},
  {experience_id:'EX-IC-VIL-001',name:'강화 고려 역사 체험마을',category_main:'문화/체험',category_sub:'체험마을',region_main:'IC',region_sub:'인천광역시 강화군',address:'인천광역시 강화군 강화읍 고려궁지길 35',lat:37.7478,lng:126.4893,price:'체험 1인 5,000원~',duration:'2~3시간',reservation_required:false,target_user:['가족','어린이','개인'],nearby_places:[],related_heritage_ids:[],short_description:'고려 대몽항쟁기 수도였던 강화도에서 고려 갑옷 입기·전통 활쏘기·고려청자 문양 찍기 등을 체험하는 역사 테마 마을이다. 고려궁지·강화산성과 함께 방문하면 몽골 항쟁 700년 역사를 입체적으로 느낄 수 있다.',source_urls:['https://www.ganghwa.go.kr/'],data_confidence:'high',tags:['강화도','고려역사','갑옷체험','활쏘기','고려청자','대몽항쟁','인천'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~17:00',phone:'032-934-7887'},
  // 레포츠/어드벤처
  {experience_id:'EX-GW-ADV-001',name:'인제 합강 래프팅',category_main:'문화/체험',category_sub:'어드벤처/레포츠',region_main:'GW',region_sub:'강원특별자치도 인제군',address:'강원특별자치도 인제군 인제읍 합강로 8',lat:38.0608,lng:128.1711,price:'1인 40,000원~',duration:'2~3시간',reservation_required:true,target_user:['개인','커플','청년'],nearby_places:[],related_heritage_ids:[],short_description:'내린천 협곡을 따라 내려오는 강원도 대표 래프팅 코스다. 수위에 따라 난이도가 달라지는 자연 급류와 드라마틱한 바위 협곡 경관이 어우러지며, 초보자 코스부터 상급자 코스까지 선택할 수 있다.',source_urls:['https://www.inje.go.kr/tour/'],data_confidence:'high',tags:['래프팅','인제','강원','내린천','어드벤처','급류','여름여행'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'08:00~17:00 (5~10월)',phone:'033-461-4296'},
  {experience_id:'EX-GW-ADV-002',name:'평창 짚와이어 체험 (알펜시아)',category_main:'문화/체험',category_sub:'어드벤처/레포츠',region_main:'GW',region_sub:'강원특별자치도 평창군',address:'강원특별자치도 평창군 대관령면 올림픽로 715',lat:37.6637,lng:128.6935,price:'1인 30,000원~',duration:'1시간',reservation_required:true,target_user:['개인','커플','청년'],nearby_places:[],related_heritage_ids:[],short_description:'평창 알펜시아 리조트의 높은 지점에서 스키 점프대 방향으로 활강하는 짚와이어 체험이다. 최고 시속 100km로 대관령 고원과 올림픽 시설 전경을 내려다보며 스릴 넘치는 경험을 할 수 있다.',source_urls:['https://www.alpensia.com/'],data_confidence:'high',tags:['짚와이어','평창','알펜시아','어드벤처','대관령','강원','스릴체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~17:00',phone:'033-339-0000'},
  {experience_id:'EX-GJ-ADV-001',name:'광주 무등산 패러글라이딩',category_main:'문화/체험',category_sub:'어드벤처/레포츠',region_main:'GJ',region_sub:'광주광역시 동구',address:'광주광역시 동구 무등산로 781 (원효사 상단)',lat:35.1430,lng:126.9897,price:'1인 100,000원~',duration:'1~2시간 (비행 10~15분)',reservation_required:true,target_user:['개인','커플','청년'],nearby_places:[],related_heritage_ids:[],short_description:'무등산 상단에서 이륙해 광주 시내와 영산강 평야를 조망하며 하강하는 패러글라이딩 체험이다. 전문 교관 동반 2인승 탠덤 비행으로 운영되어 초보자도 안전하게 즐길 수 있다.',source_urls:['https://www.gwangju.go.kr/tour/'],data_confidence:'high',tags:['패러글라이딩','무등산','광주','어드벤처','탠덤비행','광주시내전망'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'날씨 좋은 날 운영 (요일 무관)',phone:'062-226-3434'},
  // 한옥/전통 숙박
  {experience_id:'EX-GG-HAO-001',name:'수원 화성행궁 한옥 스테이',category_main:'문화/체험',category_sub:'한옥 숙박',region_main:'GG',region_sub:'경기도 수원시',address:'경기도 수원시 팔달구 행궁로 11',lat:37.2790,lng:126.9930,price:'1박 80,000원~',duration:'1박 2일',reservation_required:true,target_user:['커플','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'유네스코 세계문화유산 수원화성 내 화성행궁 인근의 전통 한옥 숙박 시설이다. 한복 대여·전통 다도 체험·밤 화성 성곽 산책을 포함한 패키지를 운영하며 정조대왕의 효심이 담긴 화성의 역사를 느끼며 하룻밤을 보낼 수 있다.',source_urls:['https://www.swcf.or.kr/'],data_confidence:'high',tags:['수원화성','한옥스테이','행궁','유네스코','경기','전통숙박','정조대왕'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'연중 (예약 필수)',phone:'031-290-3600'},
  {experience_id:'EX-GN-HAO-001',name:'하동 악양 최참판댁 고택 체험',category_main:'문화/체험',category_sub:'한옥 숙박',region_main:'GN',region_sub:'경상남도 하동군',address:'경상남도 하동군 악양면 평사리길 66-7',lat:35.0672,lng:127.6543,price:'1박 70,000원~',duration:'1박 2일',reservation_required:true,target_user:['커플','개인'],nearby_places:[],related_heritage_ids:[],short_description:'소설 토지의 배경 평사리에 재현된 최참판댁 고택에서의 하룻밤 숙박 체험이다. 악양 들판과 지리산 섬진강을 배경으로 한 고택에서 전통 한식 조식을 즐기고 박경리 토지 문학관과 연계한 문학 여행을 즐길 수 있다.',source_urls:['https://www.hadong.go.kr/'],data_confidence:'high',tags:['최참판댁','고택체험','하동','토지','박경리','섬진강','지리산','경남'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'연중 (예약 필수)',phone:'055-880-2960'},
  // 테마박물관
  {experience_id:'EX-GG-MUS-003',name:'파주 출판도시 지혜의 숲',category_main:'문화/체험',category_sub:'박물관',region_main:'GG',region_sub:'경기도 파주시',address:'경기도 파주시 회동길 145',lat:37.7374,lng:126.7224,price:'무료',duration:'1~2시간',reservation_required:false,target_user:['개인','커플','가족'],nearby_places:[],related_heritage_ids:[],short_description:'파주 출판도시 내 50만 권의 책이 천장까지 가득 쌓인 거대 도서 창고형 도서관이다. 총 길이 200m, 3개 관에 걸쳐 출판사·학자들이 기증한 책들로 채워진 독특한 공간으로 책 향기와 압도적인 서가 미감이 특별하다.',source_urls:['https://www.forestofwisdom.or.kr/'],data_confidence:'high',tags:['지혜의숲','파주','출판도시','도서관','책','경기','무료체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~20:00 (연중무휴)',phone:'031-955-0050'},
  {experience_id:'EX-GG-MUS-004',name:'수원 국립농업박물관',category_main:'문화/체험',category_sub:'박물관',region_main:'GG',region_sub:'경기도 수원시',address:'경기도 수원시 권선구 수인로 154',lat:37.2471,lng:127.0208,price:'무료',duration:'2~3시간',reservation_required:false,target_user:['가족','어린이','개인'],nearby_places:[],related_heritage_ids:[],short_description:'2022년 개관한 아시아 최대 규모의 농업 전문 박물관이다. 선사 시대부터 현대 스마트 팜까지 농업의 역사를 체험하는 공간으로 볍씨·모내기·수확 시뮬레이션, 씨앗 도서관, 어린이 농업 체험 시설이 갖춰져 있다.',source_urls:['https://www.namuk.or.kr/'],data_confidence:'high',tags:['국립농업박물관','수원','경기','농업역사','어린이체험','스마트팜','무료박물관'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:30~17:30 (월요일 휴관)',phone:'031-8030-6400'},
  {experience_id:'EX-CB-MUS-001',name:'청주 국립청주박물관',category_main:'문화/체험',category_sub:'박물관',region_main:'CB',region_sub:'충청북도 청주시',address:'충청북도 청주시 상당구 명암로 143',lat:36.6570,lng:127.5198,price:'무료',duration:'1~2시간',reservation_required:false,target_user:['가족','개인'],nearby_places:[],related_heritage_ids:[],short_description:'청주 지역 출토 선사~조선 시대 유물과 세계 최초 금속활자본 직지심체요절 복원본을 전시하는 국립 박물관이다. 직지 관련 체험과 인쇄 역사 전시가 특색 있으며 상당산성과 함께 청주 역사 여행 거점으로 활용할 수 있다.',source_urls:['https://cheongju.museum.go.kr/'],data_confidence:'high',tags:['청주박물관','직지심체요절','금속활자','충북','청주','역사박물관','무료'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~18:00 (월요일 휴관)',phone:'043-229-6300'},
  {experience_id:'EX-JN-MUS-001',name:'목포 국립해양유물전시관',category_main:'문화/체험',category_sub:'박물관',region_main:'JN',region_sub:'전라남도 목포시',address:'전라남도 목포시 남농로 136',lat:34.7894,lng:126.3764,price:'성인 3,000원',duration:'1~2시간',reservation_required:false,target_user:['가족','개인'],nearby_places:[],related_heritage_ids:[],short_description:'신안 앞바다에서 인양된 원·고려 시대 도자기 2만여 점과 조선 시대 선박 실물을 전시하는 해양 유물 전문 박물관이다. 난파선 목선 복원 전시와 수중 발굴 체험 코너가 특색 있으며 고려청자의 실물 규모를 한눈에 볼 수 있다.',source_urls:['https://www.seamuse.go.kr/'],data_confidence:'high',tags:['국립해양유물전시관','목포','고려청자','해양유물','신안','난파선','전남'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~18:00 (월요일 휴관)',phone:'061-270-2000'},
  {experience_id:'EX-DG-MUS-001',name:'대구 국립대구박물관',category_main:'문화/체험',category_sub:'박물관',region_main:'DG',region_sub:'대구광역시 수성구',address:'대구광역시 수성구 청호로 321',lat:35.8419,lng:128.6316,price:'무료',duration:'1~2시간',reservation_required:false,target_user:['가족','개인'],nearby_places:[],related_heritage_ids:[],short_description:'삼국 시대 가야·신라 유물과 영남 지역 불교 문화재를 중심으로 전시하는 국립 박물관이다. 복원 가야 철기·신라 금관 복원품·불화 특별전시 등을 운영하며 대구 근대역사관과 함께 대구 역사 여행의 거점이 된다.',source_urls:['https://daegu.museum.go.kr/'],data_confidence:'high',tags:['국립대구박물관','대구','가야','신라','영남','불교문화재','무료박물관'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~18:00 (월요일 휴관)',phone:'053-768-6051'},
  {experience_id:'EX-US-MUS-001',name:'울산 암각화박물관',category_main:'문화/체험',category_sub:'박물관',region_main:'US',region_sub:'울산광역시 울주군',address:'울산광역시 울주군 두동면 반구대안길 254',lat:35.6106,lng:129.1622,price:'무료',duration:'1~2시간',reservation_required:false,target_user:['가족','개인'],nearby_places:[],related_heritage_ids:[],short_description:'국보 반구대 암각화(약 7,000년 전)와 천전리 각석의 신석기·청동기 암각화를 실물 크기 복제·해설로 이해하는 박물관이다. 선사인의 사냥·고래잡이 장면이 새겨진 반구대 암각화는 인류 최초의 포경 기록으로 유네스코 세계유산 등재가 추진 중이다.',source_urls:['https://bangudae.ulsan.go.kr/'],data_confidence:'high',tags:['반구대암각화','울산','선사시대','암각화','국보','고래잡이','울주군'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~18:00 (월요일 휴관)',phone:'052-229-4797'}
];

const exp = JSON.parse(fs.readFileSync(base+'data/experiences.json','utf8'));
const existingIds = new Set(exp.experiences.map(e=>e.experience_id));
const toAdd = newExps.filter(e=>!existingIds.has(e.experience_id));

exp.experiences.push(...toAdd);
exp.total = exp.experiences.length;
exp._updated = now;
fs.writeFileSync(base+'data/experiences.json', JSON.stringify(exp,null,2),'utf8');

const log = JSON.parse(fs.readFileSync(base+'logs/automation_log.json','utf8'));
log.runs.push({time:now, mode:'B', type:'체험학습', new_collected:toAdd.length, total_experiences:exp.total});
fs.writeFileSync(base+'logs/automation_log.json', JSON.stringify(log,null,2),'utf8');

console.log('체험 장소 추가:', toAdd.length+'개 / 총 체험', exp.total+'개');
toAdd.forEach(e=>console.log('  + ['+e.experience_id+']', e.name, '|', e.category_sub));
