const fs = require('fs');
const base = 'C:/Users/user/Desktop/클로드/gemkorea/';
const now = new Date().toISOString().slice(0,19);

const newExps = [
  // 전통 시장 추가
  {experience_id:'EX-DG-MKT-001',name:'대구 서문시장 야시장',category_main:'문화/체험',category_sub:'전통시장',region_main:'DG',region_sub:'대구광역시 중구',address:'대구광역시 중구 큰장로26길 45',lat:35.8697,lng:128.5900,price:'무료 입장 (먹거리 별도)',duration:'2~3시간',reservation_required:false,target_user:['개인','커플','가족'],nearby_places:[],related_heritage_ids:[],short_description:'조선 시대부터 이어온 영남 최대 규모 전통 시장에서 매주 화~일 야시장이 열린다. 납작만두·튀김·대구10미 먹거리와 함께 버스킹 공연이 펼쳐지며, 대구 근대문화거리와 인접해 함께 둘러보기 좋다.',source_urls:['https://www.seomunmarket.co.kr/'],data_confidence:'high',tags:['서문시장','대구','야시장','납작만두','튀김','대구먹거리','먹거리투어'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'야시장: 화~일 19:00~23:00',phone:'053-256-6341'},
  {experience_id:'EX-GW-MKT-002',name:'강릉 정동진 모래시계 공원 장터',category_main:'문화/체험',category_sub:'전통시장',region_main:'GW',region_sub:'강원특별자치도 강릉시',address:'강원특별자치도 강릉시 강동면 헌화로 950-39',lat:37.6786,lng:129.0292,price:'무료 입장',duration:'1~2시간',reservation_required:false,target_user:['가족','개인'],nearby_places:[],related_heritage_ids:[],short_description:'정동진 모래시계 공원 인근 해변 장터에서 오징어·홍합·명란 등 강릉 동해안 특산 해산물을 구매하고 즉석에서 먹는 해산물 장터 투어다. 일출을 보고 해산물 아침 식사로 마무리하는 정동진 여행 완성 코스다.',source_urls:['https://www.gangneung.go.kr/'],data_confidence:'high',tags:['정동진','강릉','해산물장터','오징어','홍합','동해','강원'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'07:00~18:00',phone:''},
  // 문화 체험 추가
  {experience_id:'EX-SE-CUL-002',name:'서울 국립국악원 토요공연',category_main:'문화/체험',category_sub:'문화예술',region_main:'SE',region_sub:'서울특별시 서초구',address:'서울특별시 서초구 남부순환로 2364',lat:37.4774,lng:127.0074,price:'무료',duration:'1~2시간',reservation_required:false,target_user:['가족','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'매주 토요일 국립국악원에서 무료로 진행되는 국악 공연이다. 판소리·가야금·국악 관현악·민속무용 등 전통 공연 예술을 감상하며 한국 전통 음악 문화를 접할 수 있는 가장 쉬운 방법이다.',source_urls:['https://www.gugak.go.kr/'],data_confidence:'high',tags:['국립국악원','토요공연','서울','국악','무료공연','전통음악','서초'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'매주 토요일 15:00 (무료)',phone:'02-580-3300'},
  {experience_id:'EX-JB-CUL-002',name:'전주 한옥마을 야간 투어',category_main:'문화/체험',category_sub:'야경/야간투어',region_main:'JB',region_sub:'전라북도 전주시',address:'전라북도 전주시 완산구 기린대로 99 (한옥마을 입구)',lat:35.8152,lng:127.1529,price:'무료',duration:'1~2시간',reservation_required:false,target_user:['커플','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'전주 한옥마을을 밤에 걷는 야간 투어로 낮과는 다른 분위기를 즐길 수 있다. 기와집 처마 아래 한지 등불이 켜지고 경기전 앞 광장에서 야간 시장이 열리며 전통 막걸리·한과 장터도 함께 운영된다.',source_urls:['https://hanok.jeonju.go.kr/'],data_confidence:'high',tags:['전주한옥마을','야간투어','전주','전북','야경','한지등불','경기전'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'야간: 18:00~22:00',phone:'063-282-1330'},
  // 스포츠 체험
  {experience_id:'EX-GG-SPT-001',name:'과천 경마공원 승마 체험',category_main:'문화/체험',category_sub:'승마/레포츠',region_main:'GG',region_sub:'경기도 과천시',address:'경기도 과천시 경마공원대로 107',lat:37.4325,lng:127.0019,price:'1인 10,000원~',duration:'30분~1시간',reservation_required:false,target_user:['가족','어린이'],nearby_places:[],related_heritage_ids:[],short_description:'서울경마공원 내 승마 체험장에서 말을 타는 입문 체험 프로그램이다. 평일 주간에 어린이·가족 대상 체험 승마를 운영하며 말과 가까이에서 먹이 주기와 그루밍도 할 수 있다.',source_urls:['https://www.kra.co.kr/'],data_confidence:'high',tags:['승마체험','경마공원','과천','경기','어린이','가족체험','말타기'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'화~일 10:00~17:00',phone:'02-3407-1114'},
  // 창작 공예 추가
  {experience_id:'EX-GG-MAK-003',name:'양평 천연 염색 체험',category_main:'문화/체험',category_sub:'전통공예',region_main:'GG',region_sub:'경기도 양평군',address:'경기도 양평군 양평읍 양평로 일원',lat:37.4888,lng:127.4956,price:'1인 20,000원~',duration:'2시간',reservation_required:true,target_user:['커플','개인','가족'],nearby_places:[],related_heritage_ids:[],short_description:'양평 천연 염색 공방에서 쪽·치자·황토 등 자연 재료로 스카프·손수건을 직접 염색하는 체험이다. 홀치기·매듭 기법으로 다양한 무늬를 만들고 나만의 천연 염색 소품을 가져간다.',source_urls:['https://www.yangpyeong.go.kr/'],data_confidence:'high',tags:['천연염색','양평','경기','쪽염색','공방체험','커플','자연'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~17:00',phone:'031-773-5555'},
  {experience_id:'EX-JN-MAK-001',name:'담양 대나무 공예 체험',category_main:'문화/체험',category_sub:'전통공예',region_main:'JN',region_sub:'전라남도 담양군',address:'전라남도 담양군 담양읍 죽녹원로 119 (죽물박물관)',lat:35.3217,lng:126.9898,price:'1인 15,000원',duration:'1~2시간',reservation_required:true,target_user:['가족','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'담양 죽물박물관 공방에서 대나무를 깎고 엮어 소쿠리·젓가락·소품을 만드는 전통 죽공예 체험이다. 담양이 왜 대나무의 고장인지를 배우고 직접 손으로 만든 대나무 소품을 가져간다.',source_urls:['https://www.juknokwon.go.kr/'],data_confidence:'high',tags:['대나무공예','담양','전남','죽공예','죽물박물관','전통공예','대나무'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~18:00',phone:'061-380-3151'},
  // 해양/섬 체험
  {experience_id:'EX-IC-ISL-002',name:'인천 무의도 하나개해수욕장',category_main:'문화/체험',category_sub:'자연체험',region_main:'IC',region_sub:'인천광역시 중구',address:'인천광역시 중구 무의동 하나개해수욕장',lat:37.3975,lng:126.5411,price:'무료',duration:'3~5시간',reservation_required:false,target_user:['가족','커플','개인'],nearby_places:[],related_heritage_ids:[],short_description:'인천공항 옆 무의도의 넓고 한적한 모래사장 해수욕장이다. 인천공항에서 차로 30분, 연도교로 연결돼 접근이 쉬우며 수도권에서 가장 서해답고 한적한 해수욕장으로 꼽힌다.',source_urls:['https://www.icjgss.or.kr/'],data_confidence:'high',tags:['무의도','하나개해수욕장','인천','서해','인천공항근처','한적한해변','가족여행'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'seasonal',operating_hours:'연중 (성수기: 7~8월)',phone:'032-752-4141'},
  // 전통 의례 체험
  {experience_id:'EX-GG-RIT-001',name:'수원 향교 전통 제례 체험',category_main:'문화/체험',category_sub:'역사 체험',region_main:'GG',region_sub:'경기도 수원시',address:'경기도 수원시 팔달구 향교로 107',lat:37.2741,lng:126.9948,price:'1인 5,000원',duration:'1~2시간',reservation_required:true,target_user:['가족','개인','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'조선 시대 공자 성인을 모시던 수원향교에서 전통 제례 복장을 입고 절하는 법, 향 피우는 법 등 유교 의례를 체험하는 프로그램이다. 유교 문화권 외국인 방문객에게 특히 의미 있는 체험이다.',source_urls:['https://www.suwon.go.kr/'],data_confidence:'high',tags:['향교','제례체험','수원','경기','유교문화','전통의례','외국인체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'09:00~17:00 (예약 필수)',phone:'031-246-8552'},
  // 극기 체험
  {experience_id:'EX-GW-MIL-001',name:'인제 서화 육군 부대 극기 체험',category_main:'문화/체험',category_sub:'어드벤처/레포츠',region_main:'GW',region_sub:'강원특별자치도 인제군',address:'강원특별자치도 인제군 서화면 일원',lat:38.2581,lng:128.3128,price:'1인 50,000원~',duration:'1박 2일',reservation_required:true,target_user:['청년','개인'],nearby_places:[],related_heritage_ids:[],short_description:'강원도 인제 군부대에서 운영하는 일반인 대상 군사 체험 캠프다. 행군·극기 훈련·사격 체험·구급법을 배우는 1박 2일 프로그램으로 도전정신과 체력을 키우는 극기 체험이다.',source_urls:['https://www.inje.go.kr/tour/'],data_confidence:'high',tags:['군사체험','극기훈련','인제','강원','사격체험','행군','군부대체험'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'사전 예약 필수',phone:'033-461-4296'},
  // 드라마 촬영지
  {experience_id:'EX-GG-DRM-001',name:'파주 헤이리 드라마 촬영지 투어',category_main:'문화/체험',category_sub:'문화예술',region_main:'GG',region_sub:'경기도 파주시',address:'경기도 파주시 탄현면 헤이리마을길 일원',lat:37.7374,lng:126.7224,price:'무료 (갤러리 입장 유료)',duration:'2~3시간',reservation_required:false,target_user:['개인','커플','외국인'],nearby_places:[],related_heritage_ids:[],short_description:'수십 편의 드라마·영화 촬영지로 활용된 파주 헤이리 예술마을을 탐방하는 투어다. 독특한 건축물·갤러리·카페가 어우러진 예술인 마을로 드라마 별에서 온 그대·태양의 후예 등의 촬영지다.',source_urls:['https://www.heyri.net/'],data_confidence:'high',tags:['헤이리','파주','드라마촬영지','예술마을','경기','카페투어','외국인'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'10:00~18:00 (시설별 상이)',phone:'031-946-8551'},
  {experience_id:'EX-GG-DRM-002',name:'남이섬 드라마 겨울연가 투어',category_main:'문화/체험',category_sub:'역사 체험',region_main:'GG',region_sub:'경기도 가평군',address:'경기도 가평군 가평읍 달전리 1-1',lat:37.7912,lng:127.5184,price:'선박+입장 성인 16,000원',duration:'3~4시간',reservation_required:false,target_user:['외국인','커플','가족'],nearby_places:[],related_heritage_ids:[],short_description:'드라마 겨울연가 촬영지로 전 세계 한류 팬들이 찾는 순례지 남이섬이다. 자전거 대여·메타세쿼이아 길 산책·남이섬 캐릭터 카페를 즐기며 한류 드라마의 배경을 직접 체험할 수 있다.',source_urls:['https://www.namisum.com/'],data_confidence:'high',tags:['남이섬','겨울연가','가평','경기','한류','드라마촬영지','메타세쿼이아'],tour_status:'candidate',shorts_status:'waiting',created_at:now,operation_status:'active',operating_hours:'07:30~21:00',phone:'031-580-8114'}
];

const exp = JSON.parse(fs.readFileSync(base+'data/experiences.json','utf8'));
const existingIds = new Set(exp.experiences.map(e=>e.experience_id));
const toAdd = newExps.filter(e=>!existingIds.has(e.experience_id));

exp.experiences.push(...toAdd);
exp.total = exp.experiences.length;
exp._updated = now;
fs.writeFileSync(base+'data/experiences.json', JSON.stringify(exp,null,2),'utf8');

const log = JSON.parse(fs.readFileSync(base+'logs/automation_log.json','utf8'));
log.runs.push({time:now, mode:'B', type:'체험학습', new_collected:toAdd.length, total_experiences:exp.total});
fs.writeFileSync(base+'logs/automation_log.json', JSON.stringify(log,null,2),'utf8');

console.log('체험 장소 추가:', toAdd.length+'개 / 총 체험', exp.total+'개');
toAdd.forEach(e=>console.log('  + ['+e.experience_id+']', e.name, '|', e.category_sub));
